### ISSUE TITLE
在explorer.exe开启独立进程模式下,qttabbar运行时标签会出现不能正常显示的问题

### ISSUE THREAD

**Issue by kingxi82** [indiff/qttabbar#1]
问题描述: 如题,实际显示时会只能显示为一个粗横线那么大
系统环境为windows 10 19h3(18362)
explorer.exe开启独立进程模式: (github好像不能贴图,此处文字说明)
在资源管理器explorer菜单栏选择选项,在弹出的文件夹选项窗口下选择查看,
在高级设置里勾选"在单独进程中打开文件夹窗口".

**Comment by indiff** [comment]
我设置了， 效果是这样的， 和你一样吗？
![image](https://user-images.githubusercontent.com/501276/59962557-c0084800-9519-11e9-869b-a91ca43563be.png)

**Comment by hao117** [comment]
![image](https://user-images.githubusercontent.com/4453517/71149581-fe34b900-2269-11ea-8f88-594a3bb276bc.png)
我的也不行

**Comment by indiff** [comment]
这个是不是dpi的问题

![QQ图片20191228172928](https://user-images.githubusercontent.com/501276/71541676-b31c5380-2997-11ea-92f1-3173f80f5708.png)

**Comment by indiff** [comment]
请使用新版
