### ISSUE TITLE
点选项-直接强退

### ISSUE THREAD

**Issue by gcl-l** [indiff/qttabbar#10]
安装完成后点击选项卡强制退出这种情况是什么原因。
原版qttabbar卸载完后再装的github项目1.4.
这种情况替换其他版本能解决么

**Comment by gcl-l** [comment]
补充描述：
卸载原版重启后，再安装github上这个qttabbar。
刚完成成重启资源管理器，这时默认勾选了win10查看选项卡中的两项，但是点击选项按钮会强退。
尝试重启看看有没有效。
重启完成后，github上这个qttabbar全部功能失效了，win10查看选项卡中的两项可以看到，但不是选中状态了，点击选项也不会有选中效果，很疑惑这样的bug怎么解决。

用的1.4版本尝试，还没尝试其他版本

**Comment by iwlei** [comment]
同遇到此问题，你解决了吗？

**Comment by iwlei** [comment]
我的搞定了，先卸载了所有的版本，然后清理了注册表，顺便安装了net3.5，重新安装就好了。目测是之前没有安装net3.5，装了3.5之后这插件的安装时间从之前的几秒钟变成了几分钟。

**Comment by indiff** [comment]
注意 .net framework    版本
![图片](https://user-images.githubusercontent.com/501276/75231697-da08d180-57f0-11ea-9fc2-2294452cd5be.png)

**Comment by Jaytive** [comment]
同样的问题，我的更惨，打开资源管理器直接自动重启资源管理器，.net3.5一直都开着的，卸载原版之后也清过注册表了

**Comment by HQDragon** [comment]
> 注意 .net framework 版本
> ![图片](https://user-images.githubusercontent.com/501276/75231697-da08d180-57f0-11ea-9fc2-2294452cd5be.png)

考虑到win7和win10的支持性，作者是否考虑迁移至netframework4运行时上来？

**Comment by lain-github** [comment]
同样的问题, 从1.0到1.5都试了 #33

**Comment by lain-github** [comment]
> 
> 
> 同样的问题, 从1.0到1.5都试了 #33

安装net framework3.5之后好了.

**Comment by indiff** [comment]
已修复
