### ISSUE TITLE
black text on top of dark theme in file explorer

### ISSUE THREAD

**Issue by Nautiical** [indiff/qttabbar#102]
a fresh install of windows 10 updated to version 20H2 build 19042.868. .net 4.8 and .net 3.5 installed.
the text in file explorer is black on top of the windows dark theme making it really hard to read the text 
![Screenshot 2021-03-21 131842](https://user-images.githubusercontent.com/28896237/111916501-3ddbe900-8a49-11eb-8e95-c0d1b13d8ccd.png)

**Comment by Flaflo** [comment]
Disabling the highlighted option fixed this temporarily for me. Better than nothing.

![Option](https://user-images.githubusercontent.com/12973684/113111672-b476a480-9208-11eb-9cc2-71692b459ced.png)
![Result](https://user-images.githubusercontent.com/12973684/113111846-e0922580-9208-11eb-8d3a-ed32f347d49b.png)
