### ISSUE TITLE
搜索关闭后还会跳出新窗口

### ISSUE THREAD

**Issue by iiGreece** [indiff/qttabbar#103]
**描述这个Bug**
搜索文件后 ,在搜索框点X,清除搜索内容,关闭搜索窗口,最小化窗口, 过几秒窗口就会跳出来重新搜索

**系统环境:**
 - 操作系统: [win10 2004]
 - 软件版本: [e.g. 1.5.4]

**Comment by indiff** [comment]
看能不能提供截图？ 复现不出你说的操作

**Comment by hlizard** [comment]
@indiff  我也常遇到这个现象, 不过触发条件我也还无法确定, 就是搜索框会干扰其他tab

**Comment by hlizard** [comment]
![image](https://user-images.githubusercontent.com/6994037/132326491-94a981fe-e137-4c23-83bc-4a061211ee32.png)
今天又遇到自动跳出来了

**Comment by zhxingway** [comment]
还存在这个问题
