### ISSUE TITLE
用双击的方式关闭最后一个标签，会弹出一个错误提示

### ISSUE THREAD

**Issue by goodean** [indiff/qttabbar#106]
**系统环境:**
 - 操作系统: [win7]
 - .net framework: 我也不知道是多少，好像有两个版本。
![image](https://user-images.githubusercontent.com/40910711/113946319-b957db80-983a-11eb-9355-b464db55385d.png)

 - 软件版本: [1.5.4]
 
## 问题描述：
我设置了在标签上双击就关闭该标签的方式，但如果我双击关闭最后一个标签的话，就会弹出这样的窗口（我在后面会放上异常的提示信息。）：
![image](https://user-images.githubusercontent.com/40910711/113946511-33886000-983b-11eb-991d-0ff6467a549a.png)

如果选择点击【继续】还好，窗口消失，然后没什么反应。但如果要是选择了点击【退出】那麻烦大了，explorer文件管理器会退出再启动。

explorer退出再启动，就是重启，这本不是什么大事，但这软件有一个毛病（可能在我机子上是这样的），explore重启后，菜单栏上QTTabBar消失，QTTabBar按钮消失，又要重新勾选和锁定。换句话说，那个【锁定工具栏】，根本就锁不定。

![image](https://user-images.githubusercontent.com/40910711/113946896-038d8c80-983c-11eb-9d4a-8b89bf1a8f4e.png)

### 错误提示的详细信息：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“QTabControl”。
   在 System.Windows.Forms.Control.CreateHandle()
   在 System.Windows.Forms.Control.get_Handle()
   在 System.Windows.Forms.Control.PointToClientInternal(Point p)
   在 System.Windows.Forms.Control.PointToClient(Point p)
   在 QTTabBarLib.QTabControl.GetTabMouseOn()
   在 QTTabBarLib.QTTabBarClass.tabControl1_MouseUp(Object sender, MouseEventArgs e)
   在 QTTabBarLib.QTabControl.OnMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 QTTabBarLib.QTabControl.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8806 (QFE.050727-8800)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
QTTabBar
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8806 (QFE.050727-8800)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.30729.5420 built by: Win7SP1
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BandObjectLib
    程序集版本: 1.0.0.0
    Win32 版本: 2.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/BandObjectLib/1.0.0.0__973461f1cd23d8eb/BandObjectLib.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8806 (QFE.050727-8800)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
WindowsBase
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.8773 built by: QFE
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/WindowsBase/3.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.ServiceModel.Web
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.594.5458
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.ServiceModel.Web/3.5.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.8831 (QFE.030729-8800)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.8831 (QFE.030729-8800)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.ServiceModel/3.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.8831 (QFE.030729-8800)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/SMDiagnostics/3.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8773 (QFE.050727-8700)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
system.runtime.serialization.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.5420 (Win7SP1.030729-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Serialization.resources/3.0.0.0_zh-CHS_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.XML.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Xml.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
System.Transactions
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_64/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
QTPluginLib
    程序集版本: 1.0.0.0
    Win32 版本: 2.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTPluginLib/1.0.0.0__973461f1cd23d8eb/QTPluginLib.dll
----------------------------------------
QTQuick
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
TurnOffRepeat
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
CreateNewItem
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
FolderTreeButton
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
Memo
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
MigemoLoader
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTClock
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTFileTools
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTViewModeButton
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTWindowManager
    程序集版本: 1.1.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
ShowStatusBar
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
Interop.SHDocVw
    程序集版本: 1.1.0.0
    Win32 版本: 1.1.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/Interop.SHDocVw/1.1.0.0__973461f1cd23d8eb/Interop.SHDocVw.dll
----------------------------------------
PresentationFramework
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.8773 built by: QFE
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/PresentationFramework/3.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.8773 built by: QFE
    基本代码: file:///C:/Windows/assembly/GAC_64/PresentationCore/3.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
PresentationFramework.Aero
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.4902 built by: NetFXw7
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/PresentationFramework.Aero/3.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationFramework.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.4902 built by: NetFXw7
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/PresentationFramework.resources/3.0.0.0_zh-CHS_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
Ricciolo.Controls.TreeListView
    程序集版本: 1.1.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
PresentationCore.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.4902 built by: NetFXw7
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/PresentationCore.resources/3.0.0.0_zh-CHS_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
UIAutomationProvider
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.4902 built by: NetFXw7
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/UIAutomationProvider/3.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Accessibility
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by indiff** [comment]
已经修复 1.5.5 版本中解决
