### ISSUE TITLE
vs 打开文件所在位置 会报一个 无法打开此文件夹,此文件夹可能已删除或当前的权限不足

### ISSUE THREAD

**Issue by zhangjingru** [indiff/qttabbar#108]
**描述这个Bug**
vs 打开文件所在位置
会报一个 无法打开此文件夹,此文件夹可能已删除或当前的权限不足

**重现过程**
重现过程的步骤:

vs 打开文件所在位置
会报一个 无法打开此文件夹,此文件夹可能已删除或当前的权限不足
![vsqttabar](https://user-images.githubusercontent.com/14040560/115090767-56f09080-9f48-11eb-8f44-7fdf8f2bef8a.png)

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3]

**Comment by indiff** [comment]
这个是vs软件的问题，跟 qttabbar 没关系。因为弹窗是vs唤起的

**Comment by zhangjingru** [comment]
不是拉起进程返回的数据有问题吗?

**Comment by zgzs90** [comment]
尝试把软件的权限改为这个试试

<img width="514" height="290" alt="Image" src="https://github.com/user-attachments/assets/35dd8e6d-2e41-4b90-8188-2bf6b00b1e0a" />
