### ISSUE TITLE
如何设置才能兼容深色模式？

### ISSUE THREAD

**Issue by jackytsu** [indiff/qttabbar#11]
目前我的设置和效果如图所示
![image](https://user-images.githubusercontent.com/608014/75415442-98019c00-5966-11ea-91b6-ecc68645555e.png)
不知道标签的背景这一块该怎样设置
目前我试过用一张纯黑的图片
但是没有效果

**Comment by indiff** [comment]
标签目前没有可以配置颜色的地方， 需要添加配置项

**Comment by TTSBZ** [comment]
我是搞了一副黑色的图片做标签背景，效果还不错。

**Comment by Kennnnnnji** [comment]
我设置了填充黑色，但是如何才能调整工具栏字体的颜色？现在部分是黑色，很奇怪
![image](https://user-images.githubusercontent.com/34367558/84803771-03b26680-b035-11ea-9629-950313a8697b.png)

**Comment by indiff** [comment]
![462b83febcca7dca5256b7060c9cdb4](https://user-images.githubusercontent.com/501276/188319514-85972769-64d8-4124-a7e5-116d912105fe.png)

**Comment by huxc573** [comment]
> 我是搞了一副黑色的图片做标签背景，效果还不错。

我是直接从窗口里面截图的，现在就等图标适配了
