### ISSUE TITLE
点击选项后，explorer崩溃

### ISSUE THREAD

**Issue by peetteerr** [indiff/qttabbar#110]
**描述这个Bug**
打开选项后，explorer崩溃

**重现过程**
重现过程的步骤:
1. 点击 工具栏的选项摁钮
2. 鼠标变成漏斗，等待
3. 文件管理器奔溃，退回桌面，explorer重启

**期望的结果**
成功打开选项

** 本人注册表更改了window程序的标题和menu的高度（设置的比较低）**可能是崩溃原因

**系统环境:**
 - 操作系统: win10
 - .net framework: 4.0.3
 - 软件版本: 1.5.4

**Comment by FedorAdo** [comment]
Windows 10  20H2
netframework - 3.5, 4.8
1.5.4-beta

How to use the program if you cannot start its settings? ) Explorer crashes. Sorry for bad English.

**Comment by indiff** [comment]
目前软件是基于 .net framwork 3.5 编译的需要激活一下 .net 3.5 。感谢关注！
