### ISSUE TITLE
激活/非激活 标签(背景，不是文字）设置不同颜色填充

### ISSUE THREAD

**Issue by 95579580** [indiff/qttabbar#111]
激活/非激活 标签(背景，不是文字）设置不同颜色填充，像浏览器一样，这样可以清晰的看到激活了哪个标签

**Comment by indiff** [comment]
通过配置可以修改颜色的
![image](https://user-images.githubusercontent.com/501276/116516117-c890ed00-a8ff-11eb-8f9c-da6d972bc862.png)
![image](https://user-images.githubusercontent.com/501276/116516136-ce86ce00-a8ff-11eb-8ca1-d55b0c64c486.png)

**Comment by 95579580** [comment]
不是文字颜色，而是标签的底色
