### ISSUE TITLE
导出的配置.reg文件在另一台电脑上不起作用

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#113]
**描述这个Bug**
从A电脑中导出配置.reg文件，在B电脑双击该文件导入，发现配置不起作用(修改过的配置项)，是我姿势不对吗？

 - 操作系统: win10
 - .net framework: win10自带
 - 软件版本: 1.5.4-beta

**Comment by git10135405** [comment]
@indiff

**Comment by MAIMIHO** [comment]
@git10135405 可以 win + r -> regedit, 手动导出 [HKEY_CURRENT_USER\Software\QTTabBar], 到另外的电脑导入. 

软件里面导出少了很多, 所以有些配置没起作用

**Comment by git10135405** [comment]
> @git10135405 可以 win + r -> regedit, 手动导出 [HKEY_CURRENT_USER\Software\QTTabBar], 到另外的电脑导入.
> 
> 软件里面导出少了很多, 所以有些配置没起作用

最新测试版修复了吗？

**Comment by indiff** [comment]
提供一下注册表
