### ISSUE TITLE
依旧没有解决打开设置闪退问题

### ISSUE THREAD

**Issue by P0sce3fa** [indiff/qttabbar#115]
Windows 10 20H1（19042.964）

QtTabBar 1.5.5

已安装.NET 3.5
已删除程序 + 删除注册表 **重启之后** 再安装

**Comment by indiff** [comment]
提供一下你的报错日志

**Comment by kannad** [comment]
> 提供一下你的报错日志

appdata 里面没有log 桌面也没有生成crash log

**Comment by indiff** [comment]
"C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log"
一般是这个位置

**Comment by kannad** [comment]
> "C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log"
> 一般是这个位置

没有生成

**Comment by kannad** [comment]
由于我自己没有图床，具体截图在QQ发给你了

**Comment by indiff** [comment]
已修复
