### ISSUE TITLE
English Language for installer

### ISSUE THREAD

**Issue by misterchr0m3** [indiff/qttabbar#117]
Is there an English version for the installer?
Or can I update from the old version I have?
QTTabBar ver 1043 for 64bit (2020-12-20, 12-26)

**Comment by leveltrauma** [comment]
The untouched wix installer has english language files you can grab it in the folder Installer.

**Comment by yllekz** [comment]
Can someone provide a writeup on how to install these language files?

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/128129871-3b5dcd0d-4797-4a6d-a22f-d0a650f7d377.png)
