### ISSUE TITLE
文件名过长自动换行

### ISSUE THREAD

**Issue by liuchangyin** [indiff/qttabbar#118]
win10资源管理器在默认情况下“平铺”显示，文件名长是能自动换行显示的，启用QTtab后，“平铺”显示，文件名长会以"..."省略后面的文件名

**Comment by indiff** [comment]
这块windows原本就是这样的![1662525091959](https://user-images.githubusercontent.com/501276/188789213-91920655-57a7-4dc0-8549-3f295a90231b.png)
