### ISSUE TITLE
设置中检查更新按钮不可用

### ISSUE THREAD

**Issue by pencilheart** [indiff/qttabbar#119]
设置中检查更新按钮不可用。

重现过程的步骤:
1. 点击 '设置-常规选项-网络-现在检查'
2. 显示报错：“未知的网络错误”
3. 打开或关闭全局代理都没有用。

![image](https://user-images.githubusercontent.com/61617063/118742023-30dd4980-b882-11eb-9813-18fec23b752a.png)

 - 操作系统: win10
 - .net framework: 3.5
 - 软件版本: Qttabbar 1.5.4

**Comment by indiff** [comment]
已修复
