### ISSUE TITLE
最新版本不能打开设置

### ISSUE THREAD

**Issue by nanshens** [indiff/qttabbar#121]
**描述这个Bug**
清晰的Bug描述.
最新版本不能打开设置, 闪退 重启资源管理器, 是否需要net3,5 ?

**重现过程**
重现过程的步骤:
1. 点击 '...'
2. 打开 '....'
3. 滚动 '....'
4. 报错信息

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题
![image](https://user-images.githubusercontent.com/29112598/118958386-f49a0e00-b993-11eb-937f-5f552dfb4724.png)

**系统环境:**
 - 操作系统: [e.g. win10] win10 20H2 专业版
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3] 1.5.5

**Comment by pgain2004** [comment]
1.5.5版还是点设置就出错退出，修复了个寂寞

**Comment by mike652638** [comment]
最新版本的确存在这个问题, 我浏览器相关issue, 作者都是提到启用.NET Frame Work 3.5即可, 但我家里笔记本和公司电脑都是确认启用了.NET Frame Work 3.5和.NET Frame Work 4.8的(如下图), 点击选项依然会崩溃-重启资源管理器[无法打开设置界面]。

已尝试过去掉.NET Frame Work 3.5和.NET Frame Work 4.8勾选, 重启电脑-重新勾选.NET Frame Work 3.5和.NET Frame Work 4.8, 无效;

用Revo Uninstaller完全卸载Qttabbar, 再重装, 问题依然存在 ... 

还望作者加油优化哦, 辛苦了 @indiff 

![360截图18720120109116138](https://user-images.githubusercontent.com/21060980/129212457-f938d08d-3f6e-4668-86e4-3a417afaaf8d.png)

**Comment by indiff** [comment]
是因为发布的版本有问题， 然后当当晚更新过版本， 但是因为多个平台的问题，导致有一个安装包没更新
