### ISSUE TITLE
资源管理器导航窗格 > 鼠标动作

### ISSUE THREAD

**Issue by akaydev-coder** [indiff/qttabbar#122]
注：用deepl翻译

你们好，感谢你们让QTTabbar继续存在！我想说的是，你们是我的朋友。
我已经为这个伟大的项目做出了贡献，同时还写了一封邮件，询问您是否需要我的德语翻译文件用于您的项目。如果您有兴趣，请告诉我!
我的建议 如果能用鼠标中键在导航窗格中创建一个新的标签，那就很酷了。用光标悬停一个项目，然后点击它在一个新的标签页中打开它，就像quizo的qttabbar一样。
请看我附上的屏幕截图。
如果我可以提供额外的支持，请告诉我。

最好的祝愿

![qttab](https://user-images.githubusercontent.com/12538957/119005147-7f2c3e80-b98f-11eb-94a4-36bbb62773f9.jpg)

**Comment by indiff** [comment]
我的德国好朋友：
  感谢关注这个项目，您的意见已经收到！导航添加到新标签是一个很酷的点子。最后祝你生活愉快，家庭和睦！

### 使用谷歌翻译/mit Google Translate 
Mein guter Freund aus Deutschland:
   Vielen Dank für Ihr Interesse an diesem Projekt, Ihre Kommentare sind eingegangen! Das Hinzufügen einer Navigation zur neuen Registerkarte ist eine coole Idee. Zum Schluss wünsche ich Ihnen ein glückliches Leben und Familienharmonie!

**Comment by terrytw** [comment]
我们中国好朋友们也提出过
https://github.com/indiff/qttabbar/issues/84
https://github.com/indiff/qttabbar/issues/56

耐心期待中

**Comment by indiff** [comment]
最新版本已经支持
