### ISSUE TITLE
QTTabBar-1.5.5.0, Win10 21H1(19043), 偶现点击+号报错: System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。 参数名: index

### ISSUE THREAD

**Issue by mike652638** [indiff/qttabbar#123]
**描述这个Bug**
清晰的Bug描述.

**重现过程**
重现过程的步骤:
1. 点击 '蓝色+号'新建标签, 偶现BUG(详情参考下方截图或日志), 报错后会导致资源管理器失去响应或QtTabBar标签及按钮栏消失;

**截图**
![scr1](https://user-images.githubusercontent.com/21060980/119262738-e73c8800-bc0e-11eb-8153-9b62ac4d9c7d.png)
![scr2](https://user-images.githubusercontent.com/21060980/119262745-ec013c00-bc0e-11eb-899f-94e07ed111e5.png)
![scr3](https://user-images.githubusercontent.com/21060980/119262750-eefc2c80-bc0e-11eb-82de-a6b625e8f5cf.png)

相关日志(QTTabBarException.log):
2021/5/23 21:06:23
.NET 版本: 2.0.50727.9151
操作系统版本: 10.0.19043.0
QT 版本: DevBuild: 2021/5/6 17:10:18

Message ---
索引超出范围。必须为非负值并小于集合大小。
参数名: index

HelpLink ---

Source ---
mscorlib

StackTrace ---
   在 System.Collections.ArrayList.get_Item(Int32 index)
   在 System.Windows.Forms.ImageList.ImageCollection.IndexOfKey(String key)
   在 System.Windows.Forms.ImageList.ImageCollection.ContainsKey(String key)
   在 QTTabBarLib.QTUtility.SetImageKey(String key, String itemPath)
   在 QTTabBarLib.QTUtility.GetImageKey(String path, String ext)
   在 QTTabBarLib.QTabItem.set_ImageKey(String value)
   在 QTTabBarLib.QTabItem.NavigatedTo(String path, Byte[] idl, Int32 hash, Boolean autoNav)
   在 QTTabBarLib.QTTabBarClass.Explorer_NavigateComplete2(Object pDisp, Object& URL)

TargetSite ---
System.Object get_Item(Int32)
--------------

报错详细信息:
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.get_Item(Int32 index)
   在 System.Windows.Forms.ImageList.ImageCollection.IndexOfKey(String key)
   在 System.Windows.Forms.ImageList.ImageCollection.ContainsKey(String key)
   在 QTTabBarLib.QTUtility.SetImageKey(String key, String itemPath)
   在 QTTabBarLib.QTUtility.GetImageKey(String path, String ext)
   在 QTTabBarLib.QTabItem.set_ImageKey(String value)
   在 QTTabBarLib.QTabItem..ctor(String title, String path, QTabControl parent)
   在 QTTabBarLib.QTTabBarClass.CreateNewTab(IDLWrapper idlw)
   在 QTTabBarLib.QTTabBarClass.OpenNewTab(IDLWrapper idlwGiven, Boolean blockSelecting, Boolean fForceNew)
   在 QTTabBarLib.QTTabBarClass.tabControl1_PlusButtonClicked(Object sender, QTabCancelEventArgs e)
   在 QTTabBarLib.QTabControl.OnMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 QTTabBarLib.QTabControl.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9151 (WinRelRS6.050727-9100)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
QTTabBar
    程序集版本: 1.5.5.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
BandObjectLib
    程序集版本: 1.5.5.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/BandObjectLib/1.5.5.0__973461f1cd23d8eb/BandObjectLib.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Accessibility
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Core
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.30729.9141 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.ServiceModel.Web
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.594.9141
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.ServiceModel.Web/3.5.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.ServiceModel/3.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/SMDiagnostics/3.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9153 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
system.runtime.serialization.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9135 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Serialization.resources/3.0.0.0_zh-CHS_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.XML.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
System.Transactions
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_64/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Web
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9154 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_64/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.IdentityModel
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.IdentityModel/3.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
WindowsBase
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9150 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/WindowsBase/3.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
QTPluginLib
    程序集版本: 1.5.5.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTPluginLib/1.5.5.0__973461f1cd23d8eb/QTPluginLib.dll
----------------------------------------
QTQuick
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
TurnOffRepeat
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
CreateNewItem
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
FolderTreeButton
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
Memo
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
MigemoLoader
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTClock
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTFileTools
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTViewModeButton
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
QTWindowManager
    程序集版本: 1.1.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
ShowStatusBar
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
ActivateByMouseHover
    程序集版本: 1.0.0.0
    Win32 版本: 1.5.5.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.5.5.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
Interop.SHDocVw
    程序集版本: 1.1.0.0
    Win32 版本: 1.1.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/Interop.SHDocVw/1.1.0.0__973461f1cd23d8eb/Interop.SHDocVw.dll
----------------------------------------
System.Drawing.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing.resources/2.0.0.0_zh-CHS_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9151 (WinRelRS6.050727-9100)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
PresentationFramework
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9150 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/PresentationFramework/3.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9150 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_64/PresentationCore/3.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9149 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

偶现, 暂无法稳定复现, 谢谢 :)

**Comment by onergang** [comment]
@mike652638 我的电脑是必现的。感觉是设置了图片背景后又取消掉，导致异常。

**Comment by indiff** [comment]
最新版本已经修复

**Comment by onergang** [comment]
您好，您的邮件我已经收到了。我会尽快给您回复。
