### ISSUE TITLE
期望对深色模式更好的支持

### ISSUE THREAD

**Issue by MAIMIHO** [indiff/qttabbar#124]
![image](https://user-images.githubusercontent.com/18633356/119944044-60006300-bfc6-11eb-9a8a-bcee6e3ed205.png)
工具栏文字在深色模式看不清, 期望开放工具栏文字自定义.

**Comment by wlm3201** [comment]
![屏幕截图(158)](https://user-images.githubusercontent.com/77601125/122241135-e688d000-cef4-11eb-9651-b3e8cb8bb9d7.png)
确实，不忍直视

**Comment by MAIMIHO** [comment]
@wlm3201 你这样倒不至于, 要改改设置. 这是目前的版本的效果
![image](https://user-images.githubusercontent.com/18633356/122244534-8b0c1180-cef7-11eb-882b-e844768e86b9.png)

**Comment by littlegao233** [comment]
同，深色模式效果还不太完善

**Comment by moep0** [comment]
> 同，深色模式效果还不太完善，希望能改进

可以不使用这个分发，http://qttabbar.wikidot.com/ 这个感觉对黑夜模式支持更好，而且也有中文支持（搭配这个皮肤使用即可，https://www.deviantart.com/unisira/art/Windows-10-Explorer-With-QTTabBar-Dark-Theme-849487079）

目前的这个分发似乎也无法使用皮肤。

**Comment by Maskbreaker** [comment]
> @wlm3201 你这样倒不至于, 要改改设置. 这是目前的版本的效果 ![image](https://user-images.githubusercontent.com/18633356/122244534-8b0c1180-cef7-11eb-882b-e844768e86b9.png)

这个设置应该怎么调呀

**Comment by BenjiaH** [comment]
> @wlm3201 你这样倒不至于, 要改改设置. 这是目前的版本的效果 ![image](https://user-images.githubusercontent.com/18633356/122244534-8b0c1180-cef7-11eb-882b-e844768e86b9.png)

请教如何设置

**Comment by MAIMIHO** [comment]
> > @wlm3201 你这样倒不至于, 要改改设置. 这是目前的版本的效果 ![image](https://user-images.githubusercontent.com/18633356/122244534-8b0c1180-cef7-11eb-882b-e844768e86b9.png)
> 
> 请教如何设置

有个地方可以设置工具栏背景, 你可以搞一图片作为背景. 图片你就到空白处截一张小图就可以了. 这样颜色就是一样的. 

另外Tab下面的一部分可以隐藏, 深色模式也看不清.

**Comment by BenjiaH** [comment]
> > > @wlm3201 你这样倒不至于, 要改改设置. 这是目前的版本的效果 ![image](https://user-images.githubusercontent.com/18633356/122244534-8b0c1180-cef7-11eb-882b-e844768e86b9.png)
> > 
> > 
> > 请教如何设置
> 
> 有个地方可以设置工具栏背景, 你可以搞一图片作为背景. 图片你就到空白处截一张小图就可以了. 这样颜色就是一样的.
> 
> 另外Tab下面的一部分可以隐藏, 深色模式也看不清.

谢谢！

**Comment by ql-isaac** [comment]
> > 同，深色模式效果还不太完善，希望能改进
> 
> 可以不使用这个分发，http://qttabbar.wikidot.com/ 这个感觉对黑夜模式支持更好，而且也有中文支持（搭配这个皮肤使用即可，[https://www.deviantart.com/unisira/art/Windows-10-Explorer-With-QTTabBar-Dark-Theme-849487079）](https://www.deviantart.com/unisira/art/Windows-10-Explorer-With-QTTabBar-Dark-Theme-849487079%EF%BC%89)
> 
> 目前的这个分发似乎也无法使用皮肤。

这个分发是不是就是原作者那个版本，没有开源的。

**Comment by indiff** [comment]
已完成大部分支持
