### ISSUE TITLE
4k分辨率下，有点错位

### ISSUE THREAD

**Issue by yichenjing** [indiff/qttabbar#125]
![image](https://user-images.githubusercontent.com/14267361/120798371-d9bcc180-c56f-11eb-910e-a20daafbd0c9.png)

**Comment by yichenjing** [comment]
![image](https://user-images.githubusercontent.com/14267361/120798448-f48f3600-c56f-11eb-856a-a7e46abda47e.png)

**Comment by terrytw** [comment]
应该是和系统的缩放有关的
2.5分辨率下也出现同样问题

如果系统缩放是100%的话应该就没这个问题了

**Comment by renmu123** [comment]
我也遇到了相同的问题
系统：win10
分辨率：2240 x 1440
缩放：150%

系统缩放修改为100%后无此问题

**Comment by tvivt** [comment]
4K屏建议还是用原作者那个2048版本，150%缩放也没什么问题

**Comment by indiff** [comment]
需要适配DPI
