### ISSUE TITLE
列表视图里深浅列目录名的文字不对齐

### ISSUE THREAD

**Issue by chen3feng** [indiff/qttabbar#129]
**描述这个Bug**
列表视图里深浅列目录名的文字不对齐

**重现过程**
必现

**期望的结构**
期望能对齐

**截图**
![image](https://user-images.githubusercontent.com/1998410/121815909-40965500-ccab-11eb-824f-b71a15391cf2.png)

**系统环境:**
 - 操作系统: [win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: 1.5.5

**Comment by indiff** [comment]
下载最新版本或者参照下面配置
![1662510085210](https://user-images.githubusercontent.com/501276/188762116-ad69de98-d87e-4c53-a125-3f418e1dfa66.png)
