### ISSUE TITLE
1.4版本点击选项提示这个，后面再点击选项卡死

### ISSUE THREAD

**Issue by luojiasheng** [indiff/qttabbar#13]
![2020-03-06_19-25-07](https://user-images.githubusercontent.com/40587520/76080941-025bb180-5fe3-11ea-8b7f-f45eea09caa4.png)

**Comment by indiff** [comment]
.net framework 的版本是多少？

**Comment by luojiasheng** [comment]
![Snipaste_2020-03-08_21-31-49](https://user-images.githubusercontent.com/40587520/76163814-6a95c900-6184-11ea-874a-879f7e798dce.png)
系统一直都是这样，没动过

**Comment by HQDragon** [comment]
windows10 2004 19041.208
点击选项按钮导致资源管理器重启，不提示异常。
另外4k高分屏初始化时字体有问题，经过崩溃重启后就会正常

**Comment by lain-github** [comment]
我试了下从1.0到1.5都是, 点击选项, 然后就卡住了, 接着资源管理器重启.

**Comment by lain-github** [comment]
> 
> 
> 我试了下从1.0到1.5都是, 点击选项, 然后就卡住了, 接着资源管理器重启.


安装net framework3.5之后好了.

**Comment by HQDragon** [comment]
> > 我试了下从1.0到1.5都是, 点击选项, 然后就卡住了, 接着资源管理器重启.
> 
> 安装net framework3.5之后好了.

在程序与功能里启用net framework3.5即可，不过仍然建议软件增加依赖项检查，显式要求用户安装该版本。
或者升级软件至.net 4.0版本以上

**Comment by lain-github** [comment]
不能是4.0以上，只能是3.5。我有4.0以上的也不行发自我的华为手机-------- 原始邮件 --------发件人： HuQin <notifications@github.com>日期： 2020年6月10日周三 15:29收件人： indiff/qttabbar <qttabbar@noreply.github.com>抄送： lain-github <18766225813@163.com>, Comment <comment@noreply.github.com>主    题： Re: [indiff/qttabbar] 1.4版本点击选项提示这个，后面再点击选项卡死 (#13)


我试了下从1.0到1.5都是, 点击选项, 然后就卡住了, 接着资源管理器重启.

安装net framework3.5之后好了.

在程序与功能里启用net framework3.5即可，不过仍然建议软件增加依赖项检查，显式要求用户安装该版本。
或者升级软件至.net 4.0版本以上

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/84343198-16aedc00-abda-11ea-8872-a654d011631f.png)
