### ISSUE TITLE
Some icons and menus don't match dark theme

### ISSUE THREAD

**Issue by nehonac** [indiff/qttabbar#130]
When dark theme is on the toolbar icons are black and can't be seen properly. Subfolder tips icon could be better as well as match DPI settings as it is small on HiDPI.

Some menus such as subfolder tips previews and toolbar right click menus are also not dark and can't be changed in settings to be dark.

**Comment by Megadeth02** [comment]
Same issue occurred with custom windows themes. Also having a medium icon size option would help with higher resolution screens.

**Comment by shodanx2** [comment]
Hello, 
I have similar issues with dark mode, please see screenshots below
My issues are black on black text, incorrectly colored grid and white toolbar in dark interface
For now I will uninstall qttbar but reply to me if you would like me to test changes in dark mode thanks
![2021-12-05 17_48_35-C__](https://user-images.githubusercontent.com/10621885/144768445-1b50ea29-d20a-4df9-b393-55d656e69a23.png)
![2021-12-05 17_49_27-This PC](https://user-images.githubusercontent.com/10621885/144768446-298bc37b-047d-477b-a1f1-223a727b1013.png)
![2021-12-05 18_25_09-This PC](https://user-images.githubusercontent.com/10621885/144768447-e3a6a347-1028-46e5-ab20-680c57d9296b.png)
![2021-12-05 18_25_35-This PC](https://user-images.githubusercontent.com/10621885/144768448-697a8fb4-f881-4a32-a9a9-620e3535b2bb.png)
![2021-12-05 18_26_02-Desktop](https://user-images.githubusercontent.com/10621885/144768449-cf8e9109-0fe2-4fe3-9f80-55f6a22238f4.png)
![2021-12-05 18_26_22-C__](https://user-images.githubusercontent.com/10621885/144768450-5ec8ee28-c597-4b24-a382-1e705ec1c485.png)

**Comment by indiff** [comment]
1.5.5.7 will fix it
see:
https://www.yuque.com/indiff/qttabbar/zqycc5
