### ISSUE TITLE
捕获合并窗口

### ISSUE THREAD

**Issue by SiMaLaoShi** [indiff/qttabbar#134]
用第三方的工具打开资源管理器不会合并窗口，已知的是
IDEA，sublime，
估计不是用Explorer 命令来打开的

**Comment by laoleyuan** [comment]
everything打开的窗口也无法捕捉。

**Comment by zicai1026** [comment]
+1

**Comment by yefenghu** [comment]
+1
我是QQ打开文件夹、微信打开文件夹、cocos打开文件夹

**Comment by Player-hub** [comment]
# Same issue
It can't capture VSCode's explorer window (when "**open file**" or "**open folder**").
**But** it does capture VSCode's "**reveal in file explorer**"

**Comment by indiff** [comment]
请使用最新版本
