### ISSUE TITLE
win11无法卸载/覆盖旧版本

### ISSUE THREAD

**Issue by shoucandanghehe** [indiff/qttabbar#135]
**bug现象:**
之前在
http://qttabbar.wikidot.com/
下载的旧版本qttabbar,更新至win11后无法运行卸载程序
提示
![image](https://user-images.githubusercontent.com/51957264/123769636-158f4080-d8fc-11eb-9316-cc33202dba4e.png)
然后重新安装git的最新release后 资源管理器内依旧是旧版

**截图**
![image](https://user-images.githubusercontent.com/51957264/123770071-89c9e400-d8fc-11eb-8d74-e773e342162c.png)
![image](https://user-images.githubusercontent.com/51957264/123770213-b120b100-d8fc-11eb-97ab-5e30035fbd3c.png)

**系统环境:**
 - 操作系统: Windows 11 专业版 22000.51
 - .net framework: 4.8
 - 软件版本: ver1043 / 1.5.5.1

**Comment by shoucandanghehe** [comment]
emm
重启一下系统好了

**Comment by pansila** [comment]
![image](https://user-images.githubusercontent.com/5125601/129557286-083e72f9-7237-4044-8fa7-76db4480de00.png)
同样问题

**Comment by shoucandanghehe** [comment]
> ![image](https://user-images.githubusercontent.com/5125601/129557286-083e72f9-7237-4044-8fa7-76db4480de00.png)
> 同样问题

我直接安装新版然后重启一下似乎就没残留了，不过资源管理器有点卡就卸载了

**Comment by pansila** [comment]
主要是原来的1043卸载不掉很讨厌，刚才重新安装了1043再卸载可以了。
