### ISSUE TITLE
能否考虑在标签页右侧增加一个“打开新标签页”的按钮(+) ?

### ISSUE THREAD

**Issue by mike652638** [indiff/qttabbar#14]
目前打开新标签页可以通过双击标签页栏空白处或快捷键CTRL+T，但对于某些小白用户(比如临时使用安装了QtTabBar电脑的朋友)，这个功能可能还是不太明显，所以能否考虑向Firefox/Chrome浏览器那样，在标签页右侧加入一个“打开新标签页”的按钮呢 ？

谢谢，可参考下方截图 
![图片](https://user-images.githubusercontent.com/21060980/76495686-53035c80-6472-11ea-8ffa-f05527720bc5.png)

**Comment by indiff** [comment]
好的

**Comment by yyx3658** [comment]
yes，老版本的1040有这个功能，很喜欢，新版怎么取消了？
