### ISSUE TITLE
win11无法启用，1043原版可以

### ISSUE THREAD

**Issue by AnimatorBullet** [indiff/qttabbar#141]
**描述这个Bug**
更新win11后，虽然可在经典模式窗口中看到qttabbar，并且Internet加载项已启用的情况下还是无法开启qttabbar，试了下原版1043ver可以正常启用

**重现过程**
重现过程的步骤:
1. 打开资源浏览器
2. 点开 '。。。'
3. 打开  选项，选择  查看
4. 勾选  在单独的进程中打开文件夹窗口
5. 之后正常去查看中启用无反应

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: windows11 22000.65
 - .net framework: [e.g. 3.5]
 - 软件版本: 当前最新

**Comment by Kristian-Lee** [comment]
请问65版win11还能打开ie管理加载项吗？我的找不到了

**Comment by indiff** [comment]
因为qttabbar是基于IE 的BHO插件形式支持资源管理器的，而 IE11计划于2025年结束生命,所以 windows 11 的版本可能需要寻找新的改造方案！感谢关注项目！

**Comment by AnimatorBullet** [comment]
> 请问65版win11还能打开ie管理加载项吗？我的找不到了

重现步骤里面就是

**Comment by AnimatorBullet** [comment]
> 因为qttabbar是基于IE 的BHO插件形式支持资源管理器的，而 IE11计划于2025年结束生命,所以 windows 11 的版本可能需要寻找新的改造方案！感谢关注项目！

辛苦了，真的超好用，期待支持win11
