### ISSUE TITLE
Crash when open control panel

### ISSUE THREAD

**Issue by emovlee** [indiff/qttabbar#143]
1.5.5.1
Windows 10 Pro 21H1

**Comment by zhucaidan** [comment]
same here, crash on Windows 10 21H1 X64

**Comment by sobuj53** [comment]
It crashes on Windows 11 Pro 21H2

**Comment by qwop** [comment]
请提供一下日志文件 please commit the log file.
"C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log"

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月22日 16:22
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [indiff/qttabbar] Crash when open control panel (#143)


It crashes on Windows 11 Pro 21H2

―

**Comment by indiff** [comment]
update new version
