### ISSUE TITLE
win+E打开文件资源管理器或者打开“此电脑”目录会未响应导致崩溃

### ISSUE THREAD

**Issue by BaiChunhui-9803** [indiff/qttabbar#144]
1.win+E打开文件资源管理器或者打开“此电脑”目录会未响应导致崩溃，经过大概1-2分钟加载后会恢复正常；
2.打开其他目录不会出现未响应的情况

是否跟我的预览之类的设置有关？

**Comment by vllbc** [comment]
我也有类似的情况 不过我的问题是每次开机第一次右键某文件会资源管理器会崩溃，之后都可以正常
