### ISSUE TITLE
备份配置文件

### ISSUE THREAD

**Issue by ChaseClimb** [indiff/qttabbar#15]
配置文件的存放路径在哪，考虑增加配置文件导入导出功能吗

**Comment by TTSBZ** [comment]
貌似导出的是注册表项，重装后直接双击导入注册表就OK了。

**Comment by ChaseClimb** [comment]
> 貌似导出的是注册表项，重装后直接双击导入注册表就OK了。

是的，备份注册表即可，谢咯
