### ISSUE TITLE
安装后不能正常使用

### ISSUE THREAD

**Issue by wjingyuan** [indiff/qttabbar#151]
从Github下载最新中文版安装后（1.5.5），打开资源管理器，点击「查看」-「选项」，能看到QTtabBar的选项，但是单击之后没有反应。
随后又网上搜，从所谓官网（https://sourceforge.net/projects/qttabbar/）下载了另一个版本（2408），安装之后，仍然不能正常使用。
在网上搜了解决方案后，单开IE加载项管理，已经启用QTtabBar，并重启了电脑。但是仍然不能正常使用。

**截图**

![image](https://user-images.githubusercontent.com/28554380/130322579-6f4f5da8-f928-4c25-83a0-bb3861da501a.png)

![image](https://user-images.githubusercontent.com/28554380/130322549-430c52b2-7a96-4c34-956f-20f12c72c735.png)

**系统环境:**
 - 操作系统: [win10]
 - .net framework: [e.g. 4.7.1]
 - 软件版本: [e.g. 1.5.5]

**Comment by pansila** [comment]
Same issue here on 1.5.5 beta2

**Comment by indiff** [comment]
启用 .net framework 3.5
