### ISSUE TITLE
不支持win11

### ISSUE THREAD

**Issue by yichenjing** [indiff/qttabbar#153]
win11  选项按钮目前被移除了，导致无法勾选该功能

**Comment by yanghuan** [comment]
我win10 安装过，通过windows update更新到win11 是可以用的，重装系统后，在win11 系统下安装，由于界面UI有变化无法找到开启的按钮

**Comment by liudonghua123** [comment]
> 我win10 安装过，通过windows update更新到win11 是可以用的，重装系统后，在win11 系统下安装，由于界面UI有变化无法找到开启的按钮

我安装了最新版的 `QTTabBar.Setup_1.5.5.3Beta_en.2021` ，win 11 的 `explorer` 上也是没找到相关设置项

**Comment by meinvtuzai** [comment]
我安装了win11居然自动能用，不用设置！！

**Comment by bling-yshs** [comment]
@indiff Win11安装qttabbar后默认就是开启的，不需要手动开，升级后消失的话，应该重装下就行

**Comment by liudonghua123** [comment]
> 作者已经在readme更新win11设置方法了, 可查看

看文档应该是中文版的这里，我试试看 https://github.com/indiff/qttabbar/wiki/Windows11%E6%98%BE%E7%A4%BA%E5%B7%A5%E5%85%B7%E6%A0%8F%E7%9A%84%E6%96%B9%E6%B3%95

我试了但还是设置不了，点选了，但不生效

![image](https://user-images.githubusercontent.com/2276718/154601782-d9016489-bfa1-4d37-99c6-c878e948268b.png)

```
C:\Users\Liu.D.H>ver

Microsoft Windows [Version 10.0.22000.527]

C:\Users\Liu.D.H>
```

**Comment by bigbbro** [comment]
> 

同点选不生效

**Comment by bigbbro** [comment]
> > 作者已经在readme更新win11设置方法了, 可查看
> 
> 看文档应该是中文版的这里，我试试看 https://github.com/indiff/qttabbar/wiki/Windows11%E6%98%BE%E7%A4%BA%E5%B7%A5%E5%85%B7%E6%A0%8F%E7%9A%84%E6%96%B9%E6%B3%95
> 
> 我试了但还是设置不了，点选了，但不生效
> 
> ![image](https://user-images.githubusercontent.com/2276718/154601782-d9016489-bfa1-4d37-99c6-c878e948268b.png)
> 
> ```
> C:\Users\Liu.D.H>ver
> 
> Microsoft Windows [Version 10.0.22000.527]
> 
> C:\Users\Liu.D.H>
> ```

同点选不生效

**Comment by indiff** [comment]
请更新至最新版
