### ISSUE TITLE
为什么没有 目录树 和 背景的颜色调节    win8.1 用户很需要这个功能啊

### ISSUE THREAD

**Issue by fzxj520** [indiff/qttabbar#156]
为什么没有 目录树 和 背景 的颜色调节   win8.1 用户很需要这个功能啊

**Comment by fzxj520** [comment]
本来用的QTTabBar_1043  重装win8.1update 后安装了没反应 只有桌面双击菜单

**Comment by indiff** [comment]
新版的已经适配暗色模式，正在内测
