### ISSUE TITLE
工具栏出现遮挡和错位

### ISSUE THREAD

**Issue by 0391** [indiff/qttabbar#157]
**描述这个Bug**工具栏出现遮挡和错位
清晰的Bug描述.  工具栏出现遮挡和错位，取消工具栏固定后，无法进行调节

**重现过程**
重现过程的步骤:
1. 点击 '...'文件管理
2. 打开 '....'
3. 滚动 '....'
4. 报错信息

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
![图片](https://user-images.githubusercontent.com/70201691/132149956-ba2e1d5a-3ea6-4556-91d1-6839b4b14d4f.png)

如果可以的话，截图说明问题

**系统环境:**W10 21h2 19043.1165    4k 缩放 225  
 - 操作系统: [e.g. win10]W10 21h2 19043.1165
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3]1.5.5.2

**Comment by indiff** [comment]
新版本的已解决，正在内测
