### ISSUE TITLE
1. 点击 '网络和Internet.' 2. 打开 '查看硬件和连接属性.' 3. 所有的文件窗口会崩溃

### ISSUE THREAD

**Issue by namazuki** [indiff/qttabbar#158]
**描述这个Bug**
1. 点击 '网络和Internet.'
2. 打开 '查看硬件和连接属性.'
3. 所有的文件窗口会崩溃
**重现过程**
重现过程的步骤:
1. 点击 '网络和Internet.'
2. 打开 '查看硬件和连接属性.'
3. 所有的文件窗口会崩溃

**期望的结构**
希望能正常地贴在现有的文件窗口上面就行

**截图**
![image](https://user-images.githubusercontent.com/46080947/132318160-93510904-7860-446b-af36-f0d8a2f88e88.png)
![image](https://user-images.githubusercontent.com/46080947/132318306-52c513f4-7c08-4f76-9e34-e307eeba1353.png)

**系统环境:**
 - 操作系统: [win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.2.beta]

**Comment by namazuki** [comment]
版本是1.5.5.2-beta

**Comment by meinvtuzai** [comment]
同样的问题，不知道怎么解决，郁闷呢

**Comment by CoolBreezeArcanine** [comment]
有同样问题

**Comment by lintx0** [comment]
+1
