### ISSUE TITLE
在Win10黑暗模式下标签页标题字体颜色显示不正常

### ISSUE THREAD

**Issue by luojunv** [indiff/qttabbar#159]
版本1.5.5.2beta（2021）zh，在Win10黑暗模式（系统设置，个性化>>颜色>>默认应用模式（暗））中，QTTabBar的标签页标题不能正常显示，如下图（背景是白色的原因是这个工具在黑暗模式不能如预期显示黑背景）：
![1微信截图_20210912152432](https://user-images.githubusercontent.com/91038146/133979747-bfbb7e18-87d0-4884-8efd-449e5ccea94d.jpg)

我的临时解决办法是：打开QTTabBar选项窗口，按“确定”关闭窗口，就正常了。如下图：
![2微信截图_20210912152504](https://user-images.githubusercontent.com/91038146/133979790-77e00ec7-0946-47d7-99af-08359faf114e.jpg)

 - 操作系统: Win10 神州网信政府版
 - .net framework:  3.5
 - 软件版本: 1.5.5.2beta/1.5.5.4beta

**Comment by hankuksui** [comment]
是的，但是可以调背景颜色，但是工具栏的字体颜色和图标颜色好像调不了

**Comment by 5wuuy5** [comment]
我的解决办法是把标签和工具栏都使用纯黑图片作为背景

**Comment by indiff** [comment]
https://github.com/StickySli/qttabbar-dark-mode-skin
参照此项目
