### ISSUE TITLE
更好地支持Win10暗色模式

### ISSUE THREAD

**Issue by TTSBZ** [indiff/qttabbar#16]
很想启用交替行颜色功能，但貌似和Win10的暗色模式冲突，即使将前景色设置为淡色，仍有一半的文字是黑色的，导致和背景混在一起，看不清。希望后续能够优化一下。

**Comment by yfdyh000** [comment]
谢谢反馈。仍在考虑能调用哪个系统颜色，或允许自定义。担心自定义增加复杂度。

**Comment by TTSBZ** [comment]
今天才发现这个版本，非常不错，比之前的版本设置简化了很多，并且默认的配置基本符合我的使用习惯，只需要更改少量配置，非常赞。
少增加复杂度是对的，期待新版本能优化这个功能。

**Comment by yfdyh000** [comment]
在 `System.Drawing.SystemColors` 中未找到适合的颜色。
也许得加选项控件：偶数行背景色，选中项文字颜色，选中项是否粗体。或者单纯启用/禁用颜色调整。

**Comment by yfdyh000** [comment]
留言搞错了项目，已删……

**Comment by TTSBZ** [comment]
@indiff 看看

**Comment by indiff** [comment]
已经在适配
![462b83febcca7dca5256b7060c9cdb4](https://user-images.githubusercontent.com/501276/188315374-c92478b7-1738-4ac1-94de-5c629440898c.png)
