### ISSUE TITLE
从explorer切换到其他窗口时偶尔会自动跳出之前的历史搜索结果页(占用已有tab)

### ISSUE THREAD

**Issue by hlizard** [indiff/qttabbar#162]
**描述这个Bug**
相关问题: https://github.com/indiff/qttabbar/issues/103

**重现过程**
不清楚触发条件, 偶尔出现

**期望的结果**
修复

**截图**
![image](https://user-images.githubusercontent.com/6994037/136883414-8ae11f18-4b19-498c-8a0d-27fd6b346ad3.png)

**系统环境:**
 - 操作系统: win10
 - .net framework: 4.8
 - 软件版本: DevBuild: 2021/6/23

**Comment by indiff** [comment]
搜索建议使用everything

**Comment by hlizard** [comment]
改用Quizo的[QTTabBar ver 2048](http://qttabbar.wdfiles.com/local--files/qttabbar1/QTTabBar%202048%20Beta2.zip)今天也遇到这个问题
