### ISSUE TITLE
连续点击标签时，有时会导致标签位置互换

### ISSUE THREAD

**Issue by TTSBZ** [indiff/qttabbar#163]
连续点击切换标签，有时会导致标签位置互换。
例如当前已经打开了标签1、2、3、4，当前停留在标签1，点击标签2，然后紧接着快速点击标签3（连着点，中间不停顿），大概率会出现标签2和3的顺序被交换的问题。我的Matebook笔记本上重现的概率还蛮高的，导致我现在点击标签都不敢连着点，只能小心翼翼地一个一个点。。。

**Comment by indiff** [comment]
标签支持拖拽操作

**Comment by TTSBZ** [comment]
不是拖拽啊。。。是点击！问题是：如果快速连续点击多个标签，会变成拖拽的效果，导致标签位置互换！明白我的意思了吗？
你可以试着快速连续点击几个标签试一下。我已经在多台不同的电脑上重现了这个问题了！
