### ISSUE TITLE
启用“子目录行为”，蓝色箭头能否修改大一点，目前的蓝色箭头有点小

### ISSUE THREAD

**Issue by Mingtu2019** [indiff/qttabbar#165]
**“子目录行为”中更改蓝色箭头大小**
- 目前蓝色箭头有点小，不太容易选中，请求改大一点

非常感谢！

**Comment by indiff** [comment]
可以改大，但是会影响到高分辨率的用户

**Comment by Mingtu2019** [comment]
> 可以改大，但是会影响到高分辨率的用户

感谢回复，设置可选选项怎么样
