### ISSUE TITLE
Incorrect background color in the "programs and components" section

### ISSUE THREAD

**Issue by Pushkin31** [indiff/qttabbar#166]
Any way to open "programs and components" and you will see a black background on the highlighted section.

<details>
<summary>screeenshots</summary>

![explorer_TdGxq1BlZh](https://user-images.githubusercontent.com/35974828/140657678-ce281caa-05db-432e-81ae-6c4a5683b4df.png)

</details>

How do I make the system background color normal?
Windows 10,any version

**Comment by indiff** [comment]
暂时无法兼容暗黑模式
