### ISSUE TITLE
微信交流群

### ISSUE THREAD

**Issue by indiff** [indiff/qttabbar#168]
![ebd8dbaa0df3998bd2077649694f236](https://user-images.githubusercontent.com/501276/142800945-7f83a632-5345-483c-bc94-9d83fe7ef40f.jpg)

**Comment by ddzy** [comment]
二维码过期了

**Comment by aronlou** [comment]
二维码过期了啊。

**Comment by iamqiz** [comment]
qq群:
1群（已满）: [157604022](https://qm.qq.com/cgi-bin/qm/qr?k=AGA5sh_6eCEYIwofpvazRxMFin8jmVI2&jump_from=webapi)
2群: [963211351](https://jq.qq.com/?_wv=1027&k=VCPD2zLH)

![image](https://user-images.githubusercontent.com/48077521/191719193-20418d04-9edd-4d95-87f0-8d0079c1beeb.png)

**Comment by RyouOo** [comment]
1.5.5.7的文件传错了啊大佬，传成皮肤了

**Comment by indiff** [comment]
QQ群已满，3群可以进：
群号 290935247
![qttabbar国内交流群③群聊二维码](https://github.com/user-attachments/assets/7a7db2c4-308d-4417-ac75-4d2724e073c8)
