### ISSUE TITLE
BUG. NULL POINTER EXCEPTION. EXPLORER CRASH

### ISSUE THREAD

**Issue by prosupermegasuperproxxx** [indiff/qttabbar#169]
**描述这个Bug**
清晰的Bug描述.
### **BUG. NULL POINTER EXCEPTION. EXPLORER CRASH.**

 - [win7]
 - .net framework: [e.g. 3.5]
 - [qttabbar 1.5.5.3]

> hotkey bug after instal or enable plugin with hotkey support , when changing some hotkey
> add this code or explorer.exe will CRASH every time
> 		                                                          
> after instal or enable plugin with hotkey support JUST click APPLY two times and then all will be ok :D
> yes. then possible change hotkey without crash.

![0001](https://user-images.githubusercontent.com/75367518/145473348-5c6f37cf-4c35-46b8-b42f-ddb06008244a.gif)

### here two files. idk how to fix it. NULL pointer exception.
_qttabbar-1.5.5.3\QTTabBar\OptionsDialog\OptionsDialog.xaml.cs
OptionsDialog.xaml.cs  line 440+_
```
private bool ProcessNewHotkey(KeyEventArgs e, Keys current, out Keys finalKey) {
            try
            {   
                ... old code ...
            }
            catch
            {
                finalKey = Keys.None;
                System.Windows.Forms.MessageBox.Show(
                "Press APPLY TWICE! 013590 ERRRORRRR   ProcessNewHotkey \n OptionsDialog.xaml.cs");
                return false;
            }
        }          
```                   

_qttabbar-1.5.5.3\QTTabBar\OptionsDialog\Options08_Keys.xaml.cs
Options08_Keys.xaml.cs line 80+_
```
private void lvwHotkeys_PreviewKeyDown(object sender, KeyEventArgs e) {
            try
            {
                ... old code ...
            }
            catch
            {
                System.Windows.Forms.MessageBox.Show(
                "Press APPLY TWICE ERRRORRRRR123 lvwHotkeys_PreviewKeyDown \n Options08_Keys.xaml.cs");
            }
        }     
```
        
        
_P>S> 
idk how to fix it. NULL pointer exception._

**Comment by indiff** [comment]
Thanks
