### ISSUE TITLE
1.5.5.3 beta 点选项按钮资源管理器崩溃

### ISSUE THREAD

**Issue by Dai-JiaLin** [indiff/qttabbar#170]
**描述这个Bug**
1.5.5.3 beta点击选项无反应，多次点击资源管理器崩溃重启。

**重现过程**
重现过程的步骤:
1. 多次点击选项按钮
2. 资源管理器崩溃

**截图**
![资源管理器崩溃xiao2](https://user-images.githubusercontent.com/50546779/145705593-90a6f325-bf47-46c5-8172-9bb1ea9c33e8.gif)

**系统环境:**
 - 操作系统: Windows10 专业版 21H2
 - .net framework: 4.0
 - 软件版本: 1.5.5.3 beta
 - CPU：i5-6267U

**Comment by Dai-JiaLin** [comment]
之前用的是1.5.5.2 beta能够正常使用，这次是直接覆盖安装了1.5.5.3

**Comment by Mingtu2019** [comment]
选项打不开了，怎么回退到1.5.5.2 beta或者导出设置啊？

**Comment by Mingtu2019** [comment]
> 选项打不开了，怎么回退到1.5.5.2 beta或者导出设置啊？

看到wiki里的解决方案了，打扰了

**Comment by Dai-JiaLin** [comment]
我也解决了，神奇，之前1.5.5.2版本能打开让我以为我.net弄好了，冇想到没弄好
