### ISSUE TITLE
不能捕获窗口

### ISSUE THREAD

**Issue by Vzz1c** [indiff/qttabbar#172]
1

**Comment by MAIMIHO** [comment]
@Vzz1c 
我和你的使用初衷相同. 

看看 资源管理器->文件夹选项, [在单独的进程中打开文件夹窗口] 是否勾选了? 
勾选了就会再开一个, 去掉就好了.

**Comment by yefenghu** [comment]
@MAIMIHO 
然而并没有什么改善
