### ISSUE TITLE
不适配系统主题与缩放

### ISSUE THREAD

**Issue by pea3nut** [indiff/qttabbar#174]
**描述这个Bug**

![image](https://user-images.githubusercontent.com/13781420/146290922-b76a0c0c-6ead-4ad3-afdc-794068db113c.png)

**重现过程**

安装完就这样，尝试过重启

**期望的结构**

1. 跟随系统主题
2. 跟随系统缩放

**系统环境:**
- 版本	Windows 10 专业版
- 版本号	21H1
- 安装日期	‎15/‎4/‎2021
- 操作系统内部版本	19043.1348
- 体验	Windows Feature Experience Pack 120.2212.3920.0
 - .net framework: 不知道
 - 软件版本:  QTTabBar.Setup_1.5.5.3Beta_zh.2021

**Comment by indiff** [comment]
最新版本已经正在内测
