### ISSUE TITLE
通过“设置”打开“其他电源设置”会导致资源管理器闪退

### ISSUE THREAD

**Issue by Taokyla** [indiff/qttabbar#175]
**描述这个Bug**
通过“设置”打开“其他电源设置”会导致资源管理器闪退，类似的还有“关于”里的"BitLocker 设置"，点击也会闪退

**重现过程**
重现过程的步骤:
1. 打开win10设置
2. 点击《系统》
3. 选择《电源和睡眠》
4. 点击《其他电源设置》
5. 能看到资源管理器闪退

**截图**
如果可以的话，截图说明问题
![闪退gif](https://user-images.githubusercontent.com/10359761/147229731-885a26a7-8e88-4d7c-b86e-8c0a3224d572.gif)

![image](https://user-images.githubusercontent.com/10359761/147229270-1a7bc769-0772-479c-a299-a3ca9f16bd57.png)

**系统环境:**
 - 操作系统: Windows 10 专业版 21H1
 - .net framework: 3.5 & 4.8
 - 软件版本: v1.5.5.3

**Comment by kerwincsc** [comment]
可以通过在选项->窗口行为中, 设置为不捕获新的explore窗口临时解决

**Comment by kerwincsc** [comment]
我刚注意到我们的版本不一致。
我更新到1.5.5.3beta后， 按你的方式并没有复现，反而出现了另一个问题：

![image](https://user-images.githubusercontent.com/16473026/147633029-54d22ae4-51d0-4dbf-b462-3b24f2662a54.png)

![image](https://user-images.githubusercontent.com/16473026/147633050-61f3ccb1-0094-42a4-b7b0-21322daf9350.png)

可以看到，控制面板相关的窗口被捕获，但是资源管理器的窗口却显示关闭，控制面板窗口打开。
切换到下载标签后，控制面板窗口关闭，资源管理器被重新打开。

系统环境：

- 版本：Windows 10 专业工作站版
- 版本号：20H2

**Comment by indiff** [comment]
建议闪退的时候，提供一下异常日志
因为我本机无法复现问题
