### ISSUE TITLE
功能请求：双击关闭按钮  将窗口缩小化到任务栏

### ISSUE THREAD

**Issue by lk583998442** [indiff/qttabbar#176]
现在单击关闭按钮 可用关闭非锁定窗口
希望添加双击关闭按钮  将窗口缩小化到任务栏
希望这两个功能同时能用谢谢

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/159902389-7b8995b0-04c9-40c9-aa9b-4e152d1456dc.png)
可以这样设置
