### ISSUE TITLE
关闭窗口后会连续弹出对话框，内容为所有打开的标签地址

### ISSUE THREAD

**Issue by TTSBZ** [indiff/qttabbar#179]
关闭资源管理器窗口后，会连续弹出多个对话框，内容为每一个打开的标签地址，点击确定后显示下一个地址，直到所有地址全部显示完。打开控制面板时也有类似的现象，会弹出一组同样的对话框，所有对话框点完后，窗口关闭，再次点击控制面板就正常了。
对话框样例如下：
![image](https://user-images.githubusercontent.com/62744274/149045307-4518d66d-92b4-4cb6-a0de-da96f4cce473.png)

**Comment by TTSBZ** [comment]
@indiff 麻烦看看这个问题哈，这个问题一直存在。当前我电脑升级到Win11之后，这个问题仍然存在。。。

**Comment by indiff** [comment]
已经处理，更新最新版本
