### ISSUE TITLE
Win10 1909专业版 18363.720 经常出现打开资源管理器之后，qttabbar没有加载的情况

### ISSUE THREAD

**Issue by SupernovaCooper** [indiff/qttabbar#18]
首先感谢大佬继续维护这个软件，没了这个软件感觉就用不了windows了。。。原版的那个qttabbar已经停更很久了，而且感觉很卡，甚至在WinServer2019上出现了干扰鼠标按键的问题。试用了一下大佬这个，很顺畅，但是小问题还是有的。希望大佬加油搞定！

比较严重的问题就是在我的系统上，首次开机打开浏览器，会出现插件无法加载的情况，表现为QTTabbar有时候会加载出来，但是QTStandardButtons菜单没有被加载上。重新选择菜单后，也不一定会出来菜单，只能关闭资源管理器，然后重新打开再次选中菜单和Qttabbar。而且我设置了上边是菜单，下边是tab，这个顺序也会乱。。。

其次就是界面略丑啊 -_-!

希望大佬加油搞定！

**Comment by transtone** [comment]
用原版吧，这个根本用不了。http://qttabbar.wikidot.com/

**Comment by Vesfree** [comment]
I have the same problem with the original qttabbar after that windows 10 update.

即使使用原始的QTTabbar我也有同样的问题

**Comment by gongway** [comment]
要在IE浏览器的加载项中加载qttabbar插件，原版和这个版本都有这个要求。

**Comment by yyx3658** [comment]
一样的问题，不生效。
