### ISSUE TITLE
想要添加法语翻译 - Add a french translation 

### ISSUE THREAD

**Issue by ManuSquall** [indiff/qttabbar#183]
大家好。

如果可能，我想开始添加法语翻译。

Hello world :-), don't know if my "Chinesse's Google translation" is accurated 😅 but i would like to begin a french translation for this project :-) based on German and Portuguese translation already present.

**Comment by indiff** [comment]
你可以提交国际化代码上来， 我会进行发布语言版本。
You can submit the international code and I will release the language version.
