### ISSUE TITLE
无法在当前标签打开文件夹

### ISSUE THREAD

**Issue by vicwjb** [indiff/qttabbar#184]
**描述这个Bug**
关闭调整工具里的“启用旧版列表视图控件”后，双击文件夹无法在当前标签继续打开，会新开一个窗口。其他设置为默认设置。

**重现过程**
按上述操作无限重现

**系统环境:**
 - 操作系统: win11
 - .net framework: 3.5
 - 软件版本: devbuild 2021/11/22

**Comment by indiff** [comment]
已经默认关闭该配置
