### ISSUE TITLE
Default click behavior - open duplicate tab of last folder instead of the browse dialog

### ISSUE THREAD

**Issue by coinzdude** [indiff/qttabbar#185]
I would like that when I click this + : 
![image](https://user-images.githubusercontent.com/58857646/153678664-443c5518-dea9-4da9-81b6-a9a5e700e9e8.png)
it simply would duplicate the folder I am last in.  It is much faster to use explorer to navigate than to use this dialog:

![image](https://user-images.githubusercontent.com/58857646/153678725-cef60d01-a983-482d-9c56-37691e25cd0c.png)

**Comment by indiff** [comment]
it's not  My version
