### ISSUE TITLE
打开控制面板会导致已打开的资源管理器自动关闭

### ISSUE THREAD

**Issue by zjr-g** [indiff/qttabbar#187]
**描述这个Bug**
在已经打开了资源管理器后，再打开控制面板会导致原来的资源管理器自动关闭

**重现过程**
重现过程的步骤:
1. 打开 资源管理器
2. 打开 控制面板
3. 资源管理器自动关闭，只留下了控制面板

**期望的结构**
当打开控制面板时，资源管理器不会自动关闭

**截图**

**系统环境:**
 - 操作系统: [e.g. win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3]

**Comment by indiff** [comment]
已修复

**Comment by freemedom** [comment]
刚好搜到这个issue
