### ISSUE TITLE
windows server 2016 支持吗

### ISSUE THREAD

**Issue by FozuBlessNoBug** [indiff/qttabbar#188]
请问windows server 2016支持不？ QTTabar原作者的最新版是不行的，安装后看不到tab标签出现

**Comment by indiff** [comment]
你好支持的， 就是 要启用 .net 3.5

**Comment by dfxsoft** [comment]
> 请问windows server 2016支持不？ QTTabar原作者的最新版是不行的，安装后看不到tab标签出现

1043版本是支持2016的，我的系统就是2016，  1043可以用，155也可以用。

**Comment by indiff** [comment]
see:
https://www.yuque.com/indiff/qttabbar/acgs64
