### ISSUE TITLE
Anyplace to get Skins/Theme/icons for QTTabbar ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [indiff/qttabbar#189]
is ther any official place where qttabbar skins are uploaded. i have been searching for whole day and could not find it. Please help.

**Comment by StickySli** [comment]
Check out my dark mode skin! https://github.com/StickySli/qttabbar-dark-mode-skin

**Comment by PhoenixCODE2322** [comment]
Thank you. i like it.

Also is there not any place/repository for QTTabbar skins, like any official or you know some ?
