### ISSUE TITLE
没明白，版本号1040，1.5.0.0.beta2，和这个1.4的是同一个软件吗？

### ISSUE THREAD

**Issue by yyx3658** [indiff/qttabbar#19]
一直用的Qttabar 1040的版本，结果发现有个同名软件是1.5.0.0 beta2，然后又找到这里，出现了1.4，这三个软件的设置选项有很大的不同，请问是同一个软件吗？

**Comment by yfdyh000** [comment]
1.5.0.0 beta2 是最早的版本，2011年停止更新了。http://qttabbar.sourceforge.net/?p=170
作者Quizo开发了一个分支，最新是v1040，目前也停更了。不过他的Twitter最近说要继续开发。http://qttabbar.wikidot.com/
这里是国人开发的又一个分支，界面和功能有所不同。

**Comment by indiff** [comment]
两个分支
