### ISSUE TITLE
Right Click Windows icon on taskbar crashes explorer.exe - Windows 11

### ISSUE THREAD

**Issue by Daniel-Worrall** [indiff/qttabbar#191]
**描述这个Bug**
Right clicking on Windows icon on the task bar on Windows 11 crashes explorer.exe 
![image](https://user-images.githubusercontent.com/21184739/156454492-bc41d309-270f-405b-9fe8-1e5b74e734c0.png)
Unable to access the context menu

**重现过程**
1. Right click Windows icon on the task bar
2. Explorer.exe crashes

**期望的结构**
Windows context menu opens

**截图**
N/A

**系统环境:**
 - Windows 11 Insiders Dev Channel from Windows 10 Education. Version 10.0.22563 Build 22563
 - .net framework: 4.8
 - QTTabBar ver 2048 beta 2 for 64bit Windows11 IP, Windows10... (2021-9-19)

<details><summary>Event Viewer Logs (CLICK ME)</summary>

Log Name:      Application
Source:        Windows Error Reporting
Date:          02/03/2022 22:02:04
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          SYSTEM
Computer:      D-Desktop04
Description:
Fault bucket 1506241939741677798, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: explorer.exe
P2: 10.0.22563.1
P3: a05aca51
P4: Taskbar.View.dll
P5: 522.4117.0.0
P6: 620701e3
P7: c0000005
P8: 00000000002c4867
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cf6859ac-2c38-4ca1-9d9a-3481e70260fd.tmp.WERInternalMetadata.xml
[WER.cf6859ac-2c38-4ca1-9d9a-3481e70260fd.tmp.WERInternalMetadata.xml](https://github.com/indiff/qttabbar/files/8173236/WER.cf6859ac-2c38-4ca1-9d9a-3481e70260fd.tmp.WERInternalMetadata.txt)

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_explorer.exe_50bf798ebceeea057b79ed86718e3bb19d555a1_47ddbcb3_8110e16d-1821-4c95-aac3-48c43dde9a23
[Report.wer](https://github.com/indiff/qttabbar/files/8173299/Report.txt)

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb737cba-9cbb-4914-8a47-250451af8c6c
Report Status: 268435456
Hashed bucket: eea136fc23dc74ba64e73f10541918e6
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-03-02T22:02:04.7433298Z" />
    <EventRecordID>948</EventRecordID>
    <Correlation />
    <Execution ProcessID="46980" ThreadID="46992" />
    <Channel>Application</Channel>
    <Computer>D-Desktop04</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Bucket">1506241939741677798</Data>
    <Data Name="BucketType">4</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">explorer.exe</Data>
    <Data Name="P2">10.0.22563.1</Data>
    <Data Name="P3">a05aca51</Data>
    <Data Name="P4">Taskbar.View.dll</Data>
    <Data Name="P5">522.4117.0.0</Data>
    <Data Name="P6">620701e3</Data>
    <Data Name="P7">c0000005</Data>
    <Data Name="P8">00000000002c4867</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cf6859ac-2c38-4ca1-9d9a-3481e70260fd.tmp.WERInternalMetadata.xml</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_explorer.exe_50bf798ebceeea057b79ed86718e3bb19d555a1_47ddbcb3_8110e16d-1821-4c95-aac3-48c43dde9a23</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">cb737cba-9cbb-4914-8a47-250451af8c6c</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">eea136fc23dc74ba64e73f10541918e6</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Microsoft-Windows-Winlogon
Date:          02/03/2022 22:02:04
Event ID:      1002
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      D-Desktop04
Description:
The shell stopped unexpectedly and explorer.exe was restarted.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Winlogon" Guid="{DBE9B383-7CF3-4331-91CC-A3CB16A3B538}" EventSourceName="Winlogon" />
    <EventID Qualifiers="16384">1002</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-03-02T22:02:04.2967029Z" />
    <EventRecordID>947</EventRecordID>
    <Correlation />
    <Execution ProcessID="1484" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>D-Desktop04</Computer>
    <Security />
  </System>
  <EventData>
    <Data>explorer.exe</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Windows Error Reporting
Date:          02/03/2022 22:02:03
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          D-DESKTOP04\Daniel
Computer:      D-Desktop04
Description:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: explorer.exe
P2: 10.0.22563.1
P3: a05aca51
P4: Taskbar.View.dll
P5: 522.4117.0.0
P6: 620701e3
P7: c0000005
P8: 00000000002c4867
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_explorer.exe_50bf798ebceeea057b79ed86718e3bb19d555a1_47ddbcb3_8110e16d-1821-4c95-aac3-48c43dde9a23
[Report.wer](https://github.com/indiff/qttabbar/files/8173299/Report.txt)

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb737cba-9cbb-4914-8a47-250451af8c6c
Report Status: 4
Hashed bucket: 
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-03-02T22:02:03.8470082Z" />
    <EventRecordID>946</EventRecordID>
    <Correlation />
    <Execution ProcessID="46652" ThreadID="46972" />
    <Channel>Application</Channel>
    <Computer>D-Desktop04</Computer>
    <Security UserID="S-1-5-21-3859180364-15652035-2909225289-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">
    </Data>
    <Data Name="BucketType">0</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">explorer.exe</Data>
    <Data Name="P2">10.0.22563.1</Data>
    <Data Name="P3">a05aca51</Data>
    <Data Name="P4">Taskbar.View.dll</Data>
    <Data Name="P5">522.4117.0.0</Data>
    <Data Name="P6">620701e3</Data>
    <Data Name="P7">c0000005</Data>
    <Data Name="P8">00000000002c4867</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
    </Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_explorer.exe_50bf798ebceeea057b79ed86718e3bb19d555a1_47ddbcb3_8110e16d-1821-4c95-aac3-48c43dde9a23</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">cb737cba-9cbb-4914-8a47-250451af8c6c</Data>
    <Data Name="ReportStatus">4</Data>
    <Data Name="HashedBucket">
    </Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          02/03/2022 22:02:03
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          D-DESKTOP04\Daniel
Computer:      D-Desktop04
Description:
Faulting application name: explorer.exe, version: 10.0.22563.1, time stamp: 0xa05aca51
Faulting module name: Taskbar.View.dll, version: 522.4117.0.0, time stamp: 0x620701e3
Exception code: 0xc0000005
Fault offset: 0x00000000002c4867
Faulting process ID: 0x0xA680
Faulting application start time: 0x0x1D82E80F2AE6E5D
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\Taskbar.View.dll
Report ID: cb737cba-9cbb-4914-8a47-250451af8c6c
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-03-02T22:02:03.1224096Z" />
    <EventRecordID>945</EventRecordID>
    <Correlation />
    <Execution ProcessID="46652" ThreadID="46972" />
    <Channel>Application</Channel>
    <Computer>D-Desktop04</Computer>
    <Security UserID="S-1-5-21-3859180364-15652035-2909225289-1001" />
  </System>
  <EventData>
    <Data Name="AppName">explorer.exe</Data>
    <Data Name="AppVersion">10.0.22563.1</Data>
    <Data Name="AppTimeStamp">a05aca51</Data>
    <Data Name="ModuleName">Taskbar.View.dll</Data>
    <Data Name="ModuleVersion">522.4117.0.0</Data>
    <Data Name="ModuleTimeStamp">620701e3</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">00000000002c4867</Data>
    <Data Name="ProcessId">0xa680</Data>
    <Data Name="ProcessCreationTime">0x1d82e80f2ae6e5d</Data>
    <Data Name="AppPath">C:\WINDOWS\explorer.exe</Data>
    <Data Name="ModulePath">C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\Taskbar.View.dll</Data>
    <Data Name="IntegratorReportId">cb737cba-9cbb-4914-8a47-250451af8c6c</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by omaemae** [comment]
this is an Insider bug, not specific to QTTabBar

**Comment by omaemae** [comment]
but it does occur in the Insider build you're running without qttabbar.

https://user-images.githubusercontent.com/17727163/157761280-d0e912c3-92c5-4213-8541-86bdaf723e53.mp4
