### ISSUE TITLE
每当打开控制面板的时候，会同时把所有资源管理器窗口都关掉。

### ISSUE THREAD

**Issue by winteboo** [indiff/qttabbar#196]
**描述这个Bug**
每当打开控制面板的时候，会同时把所有资源管理器窗口都关掉，试了很多次都是这样

**系统环境:**
 - 操作系统: win11.22000.527
 - .net framework: 3.5 4.8
 - 软件版本: 1.5.3

**Comment by indiff** [comment]
已修复
