### ISSUE TITLE
双击文件或文件夹特别容易变成重命名

### ISSUE THREAD

**Issue by funnybones2015** [indiff/qttabbar#199]
**描述这个Bug**
双击某个文件或文件夹本想打开，结果变成了重命名

**重现过程**
重现过程的步骤:
1. 打开文件资源管理器
2.双击任意路径下的文件或文件夹

**期望的结构**
希望保持默认的打开操作

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [win11]
 - .net framework: [3.5]
 - 软件版本: [1.5.5.3]
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

**Comment by funnybones2015** [comment]
似乎把截图中的这个选项取消勾选，即可缓解双击变重命名操作的问题：

![image](https://user-images.githubusercontent.com/15063728/158737267-3906ea1e-7d9a-493a-a977-06ece295da1c.png)

有待进一步验证。。

**Comment by linguodong** [comment]
win10 双击打开文件夹感觉有时候没反应，打不开，勾了后问题也解决了。
