### ISSUE TITLE
希望可以增加标签自动排序和减重功能

### ISSUE THREAD

**Issue by fanyigle** [indiff/qttabbar#2]
谢谢作者。
1.现在看到标签可以右击并手动按名称等方式排序，希望可以加入自动排序的开关；
2.重名的标签现在是依次平铺在bar上面的，希望加入一个开关，让重名标签只能打开一个；（比如有时候从标签组里面打开一组标签，然后关了一两个，然后懒得去找，又打开一下标签组，所有的标签就都新开了，就出现重名的标签了）
![explorer_ddaImQGsrG](https://user-images.githubusercontent.com/16301390/68635023-3db50a80-0532-11ea-9a04-bc4a123c7b75.jpg)
3.另外就是lock标签好像在重启后没生效。

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/71103114-7d87a580-21f4-11ea-9d6a-3ed1b3a568ae.png)
![关重复排序](https://user-images.githubusercontent.com/501276/71102964-474a2600-21f4-11ea-81eb-9af9905056cb.gif)

**Comment by yefenghu** [comment]
大佬，不知道是不是有人提过？重复标签能不能再我要打开的时候就自动从已打开里面的去搜索，如有有就直接定位到那个标签，如果没有再新开一个标签。而不是需要手动去关闭这种?
