### ISSUE TITLE
对主题包的支持不太好，不知道怎么设置表列视图的颜色

### ISSUE THREAD

**Issue by EnderMo** [indiff/qttabbar#20]
WIN10  1803，用一个暗黑模式的主题包，表列视图里对比度太大了
![QQ截图20200417150730](https://user-images.githubusercontent.com/48214360/79542385-1e607180-80be-11ea-8dd8-bea73dd5b8e7.png)
不知道怎么调颜色
还有怎么更新

**Comment by potoo0** [comment]
我也想知道，同样需要文件列表视图颜色自定义

**Comment by potoo0** [comment]
@EnderMo 
有自定义颜色的功能，在 **调整工具** 下，如下图1 示例：
![image](https://user-images.githubusercontent.com/34411681/80054443-da53ed80-8551-11ea-8b68-1a52f435e865.png)(*figure 1*)

这样，就可以调整颜色了。通过调整此颜色就可以适应暗黑主题。

**Comment by potoo0** [comment]
我的暗色模式最终效果:

![image](https://user-images.githubusercontent.com/34411681/80056534-0de54680-8557-11ea-91f1-fcb4a5fd6747.png)

**Comment by EnderMo** [comment]
谢谢，知道了
