### ISSUE TITLE
每次开机都出现“你要如何打开这个文件”

### ISSUE THREAD

**Issue by BenjiaH** [indiff/qttabbar#203]
**描述这个Bug**
清晰的Bug描述.

**重现过程**
重现过程的步骤:
1. 电脑开机
2. 显示“你要如何打开这个文件”

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题
![2022-03-28_09-29-04_Snipper - Snipaste](https://user-images.githubusercontent.com/46958476/161408446-e7b95921-88c3-4606-bb76-4b822b9cc7f7.png)

**系统环境:**
 - 操作系统: [版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎3/‎25
操作系统版本	22581.200
体验	Windows Feature Experience Pack 1000.22581.200.0

 - .net framework: [6.0]
 - 软件版本: [1.5.3]
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
[QTTabBarException.log](https://github.com/indiff/qttabbar/files/8403682/QTTabBarException.log)

**Comment by indiff** [comment]
![图片](https://user-images.githubusercontent.com/501276/161715362-74095b36-6be9-480b-8a5a-024e009f0599.png)
添加了一个辅助功能，这个是因为官网的版本设置了这个文件。

**Comment by BenjiaH** [comment]
目前还没有这个选项，是因为版本未更新吗？
![image](https://user-images.githubusercontent.com/46958476/161717227-55a95224-ba47-4d74-99eb-f66bf53eab04.png)
