### ISSUE TITLE
Option to disable button bar.

### ISSUE THREAD

**Issue by devanteweary** [indiff/qttabbar#206]
Hello!

Thank you for the app!!

Can we have an option to disable the BUTTON BAR completely?

**Comment by ourslfs** [comment]
it's possible, unlock the toolbar, right click dotted area on the left and disable qtbar standart buttons

**Comment by devanteweary** [comment]
Oh wow I missed that. Thank you!

**Comment by shirooo39** [comment]
> it's possible, unlock the toolbar, right click dotted area on the left and disable qtbar standart buttons

This should be baked right into the Button Bar options instead of having the user figure out this way.
It took me 30 minutes just to hide/disable it...
