### ISSUE TITLE
按照win11的方法安装了，但是发现控制面板里面的Qttabbar是灰色不可选的

### ISSUE THREAD

**Issue by AK47-Plusone** [indiff/qttabbar#207]
**截图**
![image](https://user-images.githubusercontent.com/63524489/162930904-c3e49407-ded1-42cf-afd0-d09473c43e48.png)

还有个问题是视频跟图片预览功能等其他功能都没有，win11我都已经勾选net framework3.5吗，了，还是不行

**系统环境:**
 - 操作系统: win11
 - .net framework: [e.g. 3.5]
 - 软件版本: 最新版
 
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
![image](https://user-images.githubusercontent.com/63524489/162931151-5ee5b535-112e-49ce-868b-bfb8789f3349.png)
软件是已经安装了，没有问题，可以卸载的

**Comment by indiff** [comment]
确认是否启用了 .net 3.5
