### ISSUE TITLE
期望添加一个特性或者功能 [Lng_QTTabBar_Spanish.xml.]

### ISSUE THREAD

**Issue by dracp** [indiff/qttabbar#208]
Hello.

Good evening. Send language file in Spanish.
Lng_QTTabBar_Spanish.xml.

1. Greetings.
[Lng_QTTabBar_español.zip](https://github.com/indiff/qttabbar/files/8492457/Lng_QTTabBar_espanol.zip)

**Comment by indiff** [comment]
thanks yours Spanishlanguage file. 👍🙏 have a nice day !
