### ISSUE TITLE
前面打开过控制面板，再新打开资源管理器的时候，还是会有控制面板的标签呢？

### ISSUE THREAD

**Issue by modelsun** [indiff/qttabbar#210]
**描述这个Bug**
清晰的Bug描述.

**重现过程**
重现过程的步骤:
1. 点击 '...'
2. 打开 '....'
3. 滚动 '....'
4. 报错信息

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10] win10
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3]  1.5.5.4 beta
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

**Comment by indiff** [comment]
标签打开再关闭会进行保存打开的记录
