### ISSUE TITLE
关闭窗口后重新打开不会恢复上次打开的标签

### ISSUE THREAD

**Issue by dddarkkk** [indiff/qttabbar#211]
**描述这个Bug**
清晰的Bug描述.
1.win10系统，qttabbar1.5.5.4，在文件管理器的会话保存设置为恢复上一次会话所有的标签，关闭窗口后重新打开只有一个新的标签，不会恢复上次打开的标签，把设置改成只恢复上次会话锁定的标签结果也是一样
2.只有从文件管理器的默认路径打开会出现此问题，从其他文件夹路径进入能正常恢复原有的标签

**重现过程**
重现过程的步骤:
1. 打开文件管理器
2. qttabbar选项会话保存设置为恢复上一次会话所有的标签
3. 依次打开多个标签文件夹
4. 关闭窗口
5. 点击任务栏文件管理器图标重新打开文件管理器
6. 只有默认的新窗口
7. 再次关闭文件管理器

1. 打开文件管理器
2. qttabbar选项会话保存设置为恢复上一次会话所有的标签
3. 依次打开多个标签文件夹
4. 关闭窗口
5. 不选择任务栏的文件管理器图标，点击桌面其他文件夹
6. 恢复上次关闭的所有标签文件夹

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.
打开多个标签文件夹后
关闭文件管理器
重新打开文件管理器
恢复上次打开的所有标签

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.5.4]
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

**Comment by indiff** [comment]
![图片](https://user-images.githubusercontent.com/501276/169651569-2582f17a-9806-4f15-b8bc-78c9ca9efca0.png)
需要配置一下，看你自己需要哪种方式
