### ISSUE TITLE
Win11 安装最新的KB5012643 更新包后无法启动QTTabBar

### ISSUE THREAD

**Issue by zhucaidan** [indiff/qttabbar#215]
**描述这个Bug**
Win11 安装最新的KB5012643 更新包后无法启动QTTabBar

**重现过程**
重现过程的步骤:
Windows11 企业版今天的新更新包KB5012643
安装重启后无法启动QTTabBar，打开资源管理器会有错误提示音但是不显示标签
卸载此此更新后QTTabBar恢复正常
报错提示.NET错误，选择继续或者退出都无用
https://support.microsoft.com/zh-cn/topic/2022-%E5%B9%B4-4-%E6%9C%88-25-%E6%97%A5-kb5012643-os-%E5%86%85%E9%83%A8%E7%89%88%E6%9C%AC-22000-652-%E9%A2%84%E8%A7%88%E7%89%88-43a75ee7-d857-4943-a2b9-f961538bd2b0

**系统环境:**
 - 操作系统: Win11
 - .net framework: 3.5
 - 软件版本: 1.5.5.4 beta

log：
```
--------------

2022/4/26 二 3:10:22 AM
.NET 版本: 2.0.50727.9157
操作系统版本: 10.0.22000.0
QT 版本: DevBuild: 2022/3/24 四 9:18:48 AM

Message ---
未将对象引用设置到对象的实例。

HelpLink ---


Source ---
QTTabBar

StackTrace ---
   在 QTTabBarLib.QTabControl.DrawTab(Graphics g, Rectangle itemRct, Int32 index, QTabItem tabHot, Boolean fVisualStyle)
   在 QTTabBarLib.QTabControl.OnPaint_MultipleRow(PaintEventArgs e)

TargetSite ---
Void DrawTab(System.Drawing.Graphics, System.Drawing.Rectangle, Int32, QTTabBarLib.QTabItem, Boolean)
--------------

2022/4/26 二 3:10:27 AM
.NET 版本: 2.0.50727.9157
操作系统版本: 10.0.22000.0
QT 版本: DevBuild: 2022/3/24 四 9:18:48 AM

Message ---
未将对象引用设置到对象的实例。

HelpLink ---


Source ---
QTTabBar

StackTrace ---
   在 QTTabBarLib.QTabControl.DrawTab(Graphics g, Rectangle itemRct, Int32 index, QTabItem tabHot, Boolean fVisualStyle)
   在 QTTabBarLib.QTabControl.OnPaint_MultipleRow(PaintEventArgs e)

TargetSite ---
Void DrawTab(System.Drawing.Graphics, System.Drawing.Rectangle, Int32, QTTabBarLib.QTabItem, Boolean)
--------------
```

**Comment by traversebitree** [comment]
我也是，windows11更新后就不行了

**Comment by skkshu** [comment]
同(KB5012643)，启动时无法嵌入文件资源管理器

**Comment by indiff** [comment]
参考帮助 
https://github.com/indiff/qttabbar/wiki/%E5%85%B3%E4%BA%8EWindows%E6%9C%80%E6%96%B0%E8%A1%A5%E4%B8%81KB5012643--KB5012159%E5%AF%BC%E8%87%B4qttabbar%E4%BD%BF%E7%94%A8%E4%B8%8D%E4%BA%86%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95

**Comment by indiff** [comment]
原因是更新补丁影响到了 .net framework 里面的组件，需要重置一下

**Comment by songlele2007** [comment]
终于弄好了，差点儿弃用。希望作者在说明里面写一下，用win11遇到这个问题的人应该挺多的
