### ISSUE TITLE
显示bug(疑似DPI缩放问题)

### ISSUE THREAD

**Issue by unknownnumbers** [indiff/qttabbar#216]
**描述这个Bug**
在2560*1600分辨率,200%缩放的显示设置下,标签栏显示bug,且通过设置选项无法调整解决.
**重现过程**
重现过程的步骤:
1. 使用PC平台,Win11操作系统
2. 安装Github发布的软件版本
3. 在2560*1600分辨率,200%缩放的显示设置下,标签栏显示bug

**期望的结构**

增加可调选项,或实现更好的显示缩放适配

**截图**
![8QWK7h03Vr](https://user-images.githubusercontent.com/28758103/165923884-1ee244b6-6a4c-4e19-8569-b9c91e0fb4f6.png)

**系统环境:**
 - 操作系统: [win11]
 - .net framework: [不知道]
 - 软件版本: [e.g. 1.5.4]
**上传报错日志(无)

**Comment by luansheng** [comment]
存在同样的bug

**Comment by indiff** [comment]
最新的1.5.5.5版本已经修复， 近期会发布

**Comment by unknownnumbers** [comment]
> 

多谢!

**Comment by luansheng** [comment]
期待早日发布



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 中午11:23
收件人: ***@***.***&gt;;
抄送: "Sheng ***@***.******@***.***&gt;;
主题: Re: [indiff/qttabbar] 显示bug(疑似DPI缩放问题) (Issue #216)




 
最新的1.5.5.5版本已经修复， 近期会发布

**Comment by andywang666** [comment]
1.5.5.9 依旧出现类似问题，在尝试重新安装后依然出现问题。使用的msi安装包，WIN10操作系统，200%缩放。
