### ISSUE TITLE
windows 10 21H2无法使用

### ISSUE THREAD

**Issue by bireyou** [indiff/qttabbar#217]
**描述这个Bug**
Windows 10 21H2无法使用，多标签无法出现。

**系统环境:**
 - 操作系统: windows 10 21H2 版本号：19044.1682
 - .net framework: 4.8
 - 软件版本: v1.5.5.4-beta

**Comment by indiff** [comment]
看下是否更新了补丁，查看一下这个链接
https://github.com/indiff/qttabbar/wiki/%E5%85%B3%E4%BA%8EWindows%E6%9C%80%E6%96%B0%E8%A1%A5%E4%B8%81KB5012643--KB5012159%E5%AF%BC%E8%87%B4qttabbar%E4%BD%BF%E7%94%A8%E4%B8%8D%E4%BA%86%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95
