### ISSUE TITLE
菜单栏是灰色的选不了Qttabbar,IE管理加载项里是空的，第三方扩展也启用了

### ISSUE THREAD

**Issue by neko886** [indiff/qttabbar#218]
菜单栏是灰色的选不了Qttabbar,IE管理加载项里是空的，第三方扩展也启用了。
W7系统，试过不同版本的Qttabbar都一样。
![6d440f5c103853432dc495f7d613b07ecb808848](https://user-images.githubusercontent.com/103251269/166242005-6a645c85-5392-4836-a132-9604d70489a6.jpg)

![b13efc2ac65c10388675dc14f7119313b17e8948](https://user-images.githubusercontent.com/103251269/166242018-3c12fe64-abc0-4821-bd12-a5db7782c066.jpg)

**Comment by indiff** [comment]
需要启用.net3.5,重装软件
建议参照文档操作
