### ISSUE TITLE
点击关于信息里面的连接，打开了6个网页

### ISSUE THREAD

**Issue by By-Tian** [indiff/qttabbar#219]
点击关于信息里面的GitHub连接，弹出了6个GitHub的网页。上下两个GitHub的连接都是这样。
1.5.5.0Btae 4 
360极速浏览器X

**Comment by CooperZhuang** [comment]
我也遇到同样的问题，不过不能稳定复现

**Comment by indiff** [comment]
已经更换方式，点击更新打开发行版网页
