### ISSUE TITLE
捕捉新Explorer窗口功能失效

### ISSUE THREAD

**Issue by TTSBZ** [indiff/qttabbar#220]
在QTTabbar中设置捕捉新Explorer窗口为标签，按下Win+E仍然会弹出新窗口。
经常尝试，发现原因是我将资源管理器的设置中将默认打开的文件夹设置为了“此电脑”。如果将此设置改成默认的“快速访问”则不会弹出新窗口。
![image](https://user-images.githubusercontent.com/62744274/168236393-a411f2f2-6654-45d1-a0f9-70aa0f1eac09.png)

**Comment by indiff** [comment]
目前捕获新窗口有两个问题：

1. .net4版本的捕获代码不兼容
2. 捕获聊天工具打开的文件或者文件夹时候解析命令获取不到文件，所以文件不能选中
