### ISSUE TITLE
转义字符错误

### ISSUE THREAD

**Issue by BenjiaH** [indiff/qttabbar#224]
**描述这个Bug**
如图所示。
![2022-05-25_11-51-28_文件资源管理器](https://user-images.githubusercontent.com/46958476/170413704-194156c4-ed17-4d12-9c27-ecabc933e217.jpg)

**重现过程**
重现过程的步骤:
1. 弹出某个盘符（F）
2. 回退上一级到F
3. 报错信息

**期望的结构**
正确排版

**截图**
![2022-05-25_11-51-28_文件资源管理器](https://user-images.githubusercontent.com/46958476/170413704-194156c4-ed17-4d12-9c27-ecabc933e217.jpg)

**系统环境:**
 - 操作系统: [win11]
 - .net framework: [3.5]
 - 软件版本: [1.5.5.0 beta4]

**Comment by indiff** [comment]
fix 转义字符错误 #224
