### ISSUE TITLE
希望增加书签栏

### ISSUE THREAD

**Issue by Elflare** [indiff/qttabbar#23]
类似于浏览器一样的书签栏, 原版qttabbar也有, 很实用

**Comment by lystormenvoy** [comment]
看了这个issue，我想问问，这个qttabbar和那个qttabbar是什么关系啊

**Comment by lystormenvoy** [comment]
我也希望能有书签栏的功能，类似Chrome，类似Clover

**Comment by Elflare** [comment]
> 看了这个issue，我想问问，这个qttabbar和那个qttabbar是什么关系啊

这个是基于原版修改过的

**Comment by gongway** [comment]
资源管理器左侧本来就能收藏功能吧

**Comment by Elflare** [comment]
> 资源管理器左侧本来就能收藏功能吧

有,  但不能中键直接打开, 不能分组, 没有书签方便啊

**Comment by msccreater** [comment]
想问下,还是没有书签栏功能吗?真的好用

**Comment by Elflare** [comment]
> 想问下,还是没有书签栏功能吗?真的好用

没有，我用原版去了

**Comment by Subfire** [comment]
> > 想问下,还是没有书签栏功能吗?真的好用
> 
> 没有，我用原版去了

原版链接给个方便么
