### ISSUE TITLE
Open new tab in current directory

### ISSUE THREAD

**Issue by ESPGT** [indiff/qttabbar#241]
Hello developers
I want to ask you to add this feature in next builds
For example, I opened the directory C:\Users\User Name\AppData\Local and clicked open a new tab, but the My Computer window always opens. I would like to open by default the directory in which I am. It would be much more convenient.

**Comment by indiff** [comment]
你打开的是什么文件夹，则进入什么文件夹。 win+e 的意思就是打开我的电脑
