### ISSUE TITLE
Updated Spanish language file. Translation Q.1.5.5.5.B (2022)

### ISSUE THREAD

**Issue by dracp** [indiff/qttabbar#242]
Updated Spanish language file. QTTabBar 1.5.5.5 Beta (2022)

The zip contains the files: 
lang_es_ES.wxl
Lng_QTTabBar_es.xml

[Lng_QTTabBar 1.5.5.5._ES .zip](https://github.com/indiff/qttabbar/files/9333470/Lng_QTTabBar.1.5.5.5._ES.zip)

**Comment by indiff** [comment]
thanks yours Spanish language file. 👍🙏
