### ISSUE TITLE
按照redme操作，win11在控制面板勾选QTTabBar时，发现为灰色不可点击

### ISSUE THREAD

**Issue by kerna60** [indiff/qttabbar#244]
**描述这个Bug**
清晰的Bug描述.

**重现过程**
重现过程的步骤:
1. 点击 '...'
2. 打开 '....'
3. 滚动 '....'
4. 报错信息

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题
![image](https://user-images.githubusercontent.com/96719798/185306370-f1ccf445-08dd-47d6-b15f-b9fec4543067.png)

**系统环境:**
 - 操作系统: [e.g. win10]
 - 
![image](https://user-images.githubusercontent.com/96719798/185306786-74b6815b-341f-442e-8491-e505ba243831.png)

 - .net framework: [e.g. 3.5]
 - 
![image](https://user-images.githubusercontent.com/96719798/185306882-e9ca4c2a-31bc-4275-bf0a-342440068b9f.png)

 - 软件版本: v1.5.5.5-beta(2022)
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

**Comment by indiff** [comment]
检查下是否有360软件等安全软件阻止了注册表写入？

**Comment by kerna60** [comment]
> 

十分感谢，我将火绒卸载并且禁用了defender control依旧没有作用，在IE里查看加载项发现了问题，并且似乎解决了我IDM插件问题。
![image](https://user-images.githubusercontent.com/96719798/185557512-1b97662c-e57a-450d-ac2b-477404cf8db0.png)
