### ISSUE TITLE
Tabs Don't Show on Company PC

### ISSUE THREAD

**Issue by devanteweary** [indiff/qttabbar#245]
Windows 10 Pro - [Version 10.0.17763.1577]

I am on a company PC.
I have two accounts: user and admin.

If I install qttabbar using my admin account, it installs successfully but the tabs do not show.
I can even go to the toolbar and choose the qttabbar I want to show, but it doesn't actually show up.

**Comment by indiff** [comment]
Enable .net framework 3.5 ,if not you will install !
Enable the toolbar for qttabbar .
![1660840424770](https://user-images.githubusercontent.com/501276/185447660-442a068b-2944-4f7a-a346-3e1b1c122917.png)
![1660840461394](https://user-images.githubusercontent.com/501276/185447839-9c1a44be-8a23-45af-b5a1-40231cca5288.png)

**Comment by devanteweary** [comment]
@indiff , Yes it worked. Thank you!!!
