### ISSUE TITLE
标签锁定时，在右下角关闭所有会报错

### ISSUE THREAD

**Issue by meinvtuzai** [indiff/qttabbar#246]
问题：标签锁定时，在右下角关闭所有会报错
出现频率：每次都会出现
期望：不再出现提示
具体如下图所示：
![image](https://user-images.githubusercontent.com/95647691/186029108-84434c63-d7cb-41c5-9626-f955ef531d24.png)
![0](https://user-images.githubusercontent.com/95647691/186028995-705ef8f2-dbe0-4dac-a747-d956cafa5d6b.jpg)
![1](https://user-images.githubusercontent.com/95647691/186029046-f673b112-602c-41d5-8584-937c611ef653.jpg)
![2](https://user-images.githubusercontent.com/95647691/186029059-9233f446-8de5-4e22-8464-353b0b469f8e.jpg)
![3](https://user-images.githubusercontent.com/95647691/186029068-d40bc7ab-faf2-4ff2-acb7-4cf37d7e66ba.jpg)

**Comment by indiff** [comment]
已经修复
