### ISSUE TITLE
打开选项设置时的显示问题

### ISSUE THREAD

**Issue by langzijianghu** [indiff/qttabbar#25]
打开选项设置后最上面被任务栏覆盖，窗口也无法拖动。使用了透明任务栏软件。
![image](https://user-images.githubusercontent.com/57357340/82558489-56b50d00-9ba0-11ea-8d5a-31ecabaee83c.png)

**Comment by indiff** [comment]
卸载透明任务栏软件试一试， 看下是否冲突?
