### ISSUE TITLE
How to hide this blank area?

### ISSUE THREAD

**Issue by infohost** [indiff/qttabbar#250]
![image](https://user-images.githubusercontent.com/56072429/188299564-9f53e49e-d85b-48e5-b225-4d70f7cf4dad.png)

![image](https://user-images.githubusercontent.com/56072429/188299579-257bbec9-74f3-458c-8968-c5b1bcd40936.png)

**Comment by indiff** [comment]
please send the version of  os

**Comment by infohost** [comment]
> please send the version of os

Version 10.0.22621.382
EN-US

**Comment by Bobbsterman** [comment]
You need to hide the Button Bar. Right click in the blank space > deselect "Lock the Toolbars". A handle (3 little dots) will appears on the side. Right click > deselect "QTTab Standard Buttons". You can now Lock the Toolbars again.

Enhancement idea: make this easier/more obvious, by adding a toggle to hide the Tabs or Standard buttons within the Options menu.

**Comment by infohost** [comment]
Sorted. Thanks @Bobbsterman
