### ISSUE TITLE
QTTabBar Windows 11 - Greyed Out enabling option

### ISSUE THREAD

**Issue by LokeYourLord** [indiff/qttabbar#251]
![image](https://user-images.githubusercontent.com/5807595/189521536-bc0ddd4e-419d-48c7-b70e-54842b82963c.png)

As you can see, the option to turn on QTTabBar are both greyed out. Is there another way to turn on QTTabBar? I tried [QTTabBar from QuizoApps](http://qttabbar.wikidot.com/) (the original), but that one stopped working after a while. Only the bottom and side bar works, but the top bar is gone and doesn't return. So I tried this one, but it doesn't even show or work at all.

**Comment by LokeYourLord** [comment]
Add bug label please.

**Comment by indiff** [comment]
see:
https://www.yuque.com/indiff/qttabbar/ibni53
https://www.yuque.com/indiff/qttabbar/mfoxt9

**Comment by LokeYourLord** [comment]
WAIT ARE YOU SERIOUS, QTTABBAR IS AN INTERNET EXPLORER "addon"!? Omg... That was my fault then, I disabled all addons for Internet Explorer with CCleaner...
![image](https://user-images.githubusercontent.com/5807595/189522007-d04fb03a-e604-40bf-bad6-ecf097788987.png)

I enabled them again, let's see if that fixes it...

Yep, fixed it, lol...
