### ISSUE TITLE
Drag-hovering doesn't work on some folders

### ISSUE THREAD

**Issue by JRHille** [indiff/qttabbar#258]
**描述这个Bug**
It's not possible to drag-hovering in folders (Documents, Downloads, Images, Videos and Music). In the other folders of the system it's possible, but not in those mentioned.

**重现过程**
重现过程的步骤:
1. Try dragging any file into the folders (Documents, Downloads, Images, Videos and Music).

**系统环境:**
 - 操作系统: Windows 10 21H2 (19044.1826)
 - 软件版本: 1.5.5 b6

![vlc_jz9Xp5UuuT](https://user-images.githubusercontent.com/114708288/193424015-ca19479b-94ea-4cb7-a19b-751d00cd2b17.png)

Video:
https://imgur.com/a/eqCHzCg
OR
https://user-images.githubusercontent.com/114708288/193423894-85c4b455-c5c9-4ed0-995d-749d67537ff0.mp4

**Comment by JRHille** [comment]
by the way, i just installed the new beta 7 version, same problem. And this version is much slower when opening explorer :( going back to beta 6...

**Comment by indiff** [comment]
![拖动zip压缩包到标签栏](https://user-images.githubusercontent.com/501276/193452237-7d22666f-17b4-4ffe-9dc4-7c5c1101568e.gif)
