### ISSUE TITLE
希望能在文档中写明Internet Explorer中的加载项可能会禁用qttabbar

### ISSUE THREAD

**Issue by youhuangla** [indiff/qttabbar#259]
**文档中写明Internet Explorer中的加载项可能会禁用qttabbar**
我用了一年多，最近突然发现qttabbar不能使用了，安装或者重新安装后都无法在资源管理器->查看->选项中看到qttabbar。搜索Issue后没发现对应情况，检查.NET也已经启用，后发现[win10 qttabbar不可用 \- iyonghua的个人空间 \- OSCHINA \- 中文开源技术交流社区](https://my.oschina.net/u/2485283/blog/3124486#:~:text=%E8%A7%A3%E5%86%B3%20win10%20%E7%B3%BB%E7%BB%9F%20qttabbar%20%E6%8C%89%E9%92%AE%E4%B8%8D%E5%8F%AF%E7%94%A8%201.,%E6%89%93%E5%BC%80%20ie%20%E6%B5%8F%E8%A7%88%E5%99%A8%20internet%20%E9%80%89%E9%A1%B9%E7%9A%84%E7%A8%8B%E5%BA%8F%E9%A1%B5%E7%AD%BE%202.)符合我的情况。原因是Internet Explorer中的右上角设置->Internet选项->程序->管理加载项->工具栏和扩展中qttabbar被禁用，启用对应选项后可以正常使用

**Comment by indiff** [comment]
https://www.yuque.com/indiff/qttabbar/mfoxt9
