### ISSUE TITLE
加入标签关闭按钮和锁定按钮的图标自定义选项

### ISSUE THREAD

**Issue by NewbieOrange** [indiff/qttabbar#26]
希望在外观设置页中加入标签关闭按钮和锁定按钮的图标自定义图标路径，类似于另一个分支中的效果：
![图片](https://user-images.githubusercontent.com/7200314/82863124-e61d4000-9f53-11ea-9a2f-eb08728271fd.png)

**Comment by lystormenvoy** [comment]
这界面怎么完全不一样呢

**Comment by indiff** [comment]
感谢提供参考意见
