### ISSUE TITLE
最新版qttabbar操作资源管理器反应速度有些慢

### ISSUE THREAD

**Issue by xiaoxin6182** [indiff/qttabbar#265]
最新版qttabbar操作资源管理器反应速度有些慢，比老版本明显慢，win10系统，QTTabBar DevBuild:2021/1/12 16:17:40,

这个版本的速度明显比最新版qttabbar操作速度快

**Comment by indiff** [comment]
默认加载了插件的dll 和 设置背景的 dll
下个版本要推出无插件版本的，到时候你试一试
