### ISSUE TITLE
标签文本里面的阴影颜色不能保存，重新打开任务管理器后会重置

### ISSUE THREAD

**Issue by 1096495296** [indiff/qttabbar#266]
<img width="431" alt="uTools_1665410347421" src="https://user-images.githubusercontent.com/42825392/194883796-16c8d7b3-14b1-40b8-8d4d-5cc083a252d1.png">

**Comment by hxhaozi** [comment]
折磨死我这个强迫症了

**Comment by qwop** [comment]
问题正在处理

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: kanade ***@***.***>
发送时间: Thursday, October 20, 2022 11:53:41 AM
收件人: indiff/qttabbar ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [indiff/qttabbar] 标签文本里面的阴影颜色不能保存，重新打开任务管理器后会重置 (Issue #266)


折磨死我这个强迫症了

―

**Comment by llccool** [comment]
对，还有工具栏布置，标签栏和工具栏，本来设置在一行，重开后，又变回2行
