### ISSUE TITLE
如下角的人物如何关闭？

### ISSUE THREAD

**Issue by lxl217114** [indiff/qttabbar#267]
![image](https://user-images.githubusercontent.com/54263659/195235020-8c6ec652-8616-4734-8c42-9590b5c6d707.png)

**Comment by indiff** [comment]
有问题可以到群里面去问

**Comment by indiff** [comment]
有问题可以到群里面去问

**Comment by Qualiazero** [comment]
这个人用注册表强制更改了背景，我最后用了还原点才恢复注册表删除掉这个图片！千万不要再安装这个软件！

**Comment by sonicmingit** [comment]
<img width="554" alt="Snipaste_2022-12-23_00-08-49" src="https://user-images.githubusercontent.com/18570497/209175377-c520b292-ab8c-42af-8d44-d3fe36cd5bff.png">
