### ISSUE TITLE
Windows 10 LTSC 21H2 安装后选项中没有qttabbar

### ISSUE THREAD

**Issue by LiteCoder** [indiff/qttabbar#275]
```
Windows 10 企业版 LTSC
版本号	21H2
安装日期	‎2021/‎11/‎18
操作系统内部版本	19044.2006 
```
是不支持ltsc的版本吗，安装了 1.5.5.6版本和1.5.5.7版本都不行，电脑也重启过了
确认是有.net 2.0和3.5版本的
XXX\AppData\Roaming目录下也没有qttabbar，无法查看日志

**Comment by klxq520** [comment]
安装好要在加载项里启用才行的，我也是折腾了好久才搞明白，但这个版本有bug，打开资源管理器超慢，要几十秒时间，然后打不开设置页面了，一点设置就闪退窗口，建议不要安装[v1.5.5-beta.7]这个版本，先用上个版本或等下个版本吧。
启用方法：控制面板\网络和 Internet\，点击“管理浏览器加载项”，在窗口里点“管理加载项”按钮，把与qttabbar相关的都启用就行。

**Comment by LiteCoder** [comment]
> 安装好要在加载项里启用才行的，我也是折腾了好久才搞明白，但这个版本有bug，打开资源管理器超慢，要几十秒时间，然后打不开设置页面了，一点设置就闪退窗口，建议不要安装[v1.5.5-beta.7]这个版本，先用上个版本或等下个版本吧。 启用方法：控制面板\网络和 Internet\，点击“管理浏览器加载项”，在窗口里点“管理加载项”按钮，把与qttabbar相关的都启用就行。

感谢解答！我试试看

**Comment by indiff** [comment]
https://www.yuque.com/indiff/qttabbar/mfoxt9
