### ISSUE TITLE
只剩最后一个Tab时，鼠标操作和界面交互逻辑有问题

### ISSUE THREAD

**Issue by zycboss** [indiff/qttabbar#277]
**描述这个Bug**
只留一个标签时，似乎程序会认为整个“标签栏”的区域都属于这个标签的，此时鼠标操作中的点击“标签栏空白处”的操作会被认为是点击了此标签

**重现过程**
重现过程的步骤:
1. 设置鼠标操作-标签-双击-关闭标签
2. 设置鼠标操作-标签栏空白处-双击-恢复关闭的标签
3. 在有多个标签存在时，以上操作正确
4. 在仅有最后一个标签存在时，双击“标签栏空白处”会导致最后一个标签关闭，而非恢复之前关闭的标签
5. 在此情况下，只有点击下方功能按钮的空白区域，才判定为点击了“标签栏空白处”
6. 此问题可以通过设置其他不同的鼠标操作动作复现
7. 另外，只剩一个标签时，关闭标签的按钮“x”会一直显示，而非鼠标悬停时才显示，多个标签时表现正常

**期望的结构**
统一只剩一个标签时的界面和交互逻辑和多个标签时相同

**截图**
![image](https://user-images.githubusercontent.com/29044143/197463663-ad3daf3e-c2b4-44e4-80c6-db7fac0aa846.png)

**系统环境:**
 - 操作系统: [win10 20H2]
 - .net framework: [4.6]
 - 软件版本: [1.5.5.7]

**Comment by indiff** [comment]
beta8版本已经修复

**Comment by zycboss** [comment]
那么beta8在哪里可以下呢
