### ISSUE TITLE
Tab in Toolbar not visible

### ISSUE THREAD

**Issue by sobuj53** [indiff/qttabbar#279]
**描述这个Bug**
清晰的Bug描述.
Tabs are not visible in Toolbar. Also Explorer crashes while opening control panel.

**重现过程**
重现过程的步骤:
1. 点击 '...'
2. 打开 Open QTTabBar
3. 滚动 '....'
4. 报错信息

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.
![image](https://user-images.githubusercontent.com/25761237/199101807-b3d67bd8-32cf-456b-a0b8-9cb985aa0200.png)

Appearance settings
![image](https://user-images.githubusercontent.com/25761237/199103771-7e07f81d-1da4-4463-9f6b-f44df992c3f5.png)

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: win11
 - .net framework:  3.5
 - 软件版本: v1.5.5-beta.7
 - 重点、重点、重点；没有报错日志本地复现不了的话，那这个问题不会处理
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
[QTTabBarException.log](https://www.klgrth.io/paste/bt5u2)

**Comment by indiff** [comment]
the problem fixed in beta.8. you can set toolbar visible.
