### ISSUE TITLE
打开控制面板中的页面会将前面的资源管理器标签全部关闭

### ISSUE THREAD

**Issue by AGNay** [indiff/qttabbar#280]
**描述这个Bug**
打开控制面板中的页面会将前面的资源管理器标签全部关闭，望大佬修复
ps我看有反馈过win11的，不过在win10上还存在
**重现过程**
重现过程的步骤:
1. 打开任意一个标签
2. 搜索  打开 '控制面板'

**期望的结构**
控制面板作为新标签加入原资源管理器，或单独开启，并不清空原资源管理器的所有标签

**系统环境:**
 - 操作系统: [win10.21H2 19044]
 - .net framework: [3.5]
 - 软件版本: [1.5.5 bate7]

**Comment by AGNay** [comment]
测试1.5.5.8已经正常，感谢大佬

**Comment by zhxingway** [comment]
偶尔会出现的
