### ISSUE TITLE
一点设置就闪退，你们有这情况吗？

### ISSUE THREAD

**Issue by klxq520** [indiff/qttabbar#281]
就是点设置按钮就会卡住几秒，然后整个窗口都会关闭，系统是WIN10专业版，安装的是目前的最新版v1.5.5-beta.7

**Comment by Crystal-RainSlide** [comment]
有。

**Comment by indiff** [comment]
提供一下报错日志， 有可能是配置文件冲突，导致异常了

**Comment by Crystal-RainSlide** [comment]
> 提供一下报错日志， 有可能是配置文件冲突，导致异常了

全新安装。

[QTTabBarException.log](https://github.com/indiff/qttabbar/files/9936799/QTTabBarException.log)

**Comment by indiff** [comment]
你本机的时间格式被改动过， 这个在新版已经修复


_.NET 版本: 2.0.50727.9164
操作系统版本: 10.0.19043.0 Major: 10 环境: 64
QT 版本: DevBuild: 2022/10/2 8:22:45 AM (2.0.50727.9164)
错误信息: QTTabBarClass 构造函数初始化安装时间

Message ---
该字符串未被识别为有效的 DateTime。
HelpLink ---

Source ---
mscorlib
StackTrace ---
   在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   在 QTTabBarLib.QTTabBarClass..ctor()
TargetSite ---
System.DateTime Parse(System.String, System.Globalization.DateTimeFormatInfo, System.Globalization.DateTimeStyles)--------------_

**Comment by zycboss** [comment]
到控制面板里找到老版本，卸载掉就行了
装新版本不会覆盖老版本，也是醉

**Comment by royccg** [comment]
> 到控制面板里找到老版本，卸载掉就行了 装新版本不会覆盖老版本，也是醉

我也遇到这个问题，卸载了重新安装最新的 V1.5.5-beta9，还是存在相同的问题欸。

**Comment by zycboss** [comment]
> > 到控制面板里找到老版本，卸载掉就行了 装新版本不会覆盖老版本，也是醉
> 
> 我也遇到这个问题，卸载了重新安装最新的 V1.5.5-beta9，还是存在相同的问题欸。

已经放弃不用了，bug太多了，各种闪退，而且作者也不更新了
换win11可以实现大部分功能

**Comment by Crystal-RainSlide** [comment]
一直在更新，迟迟不发布
