### ISSUE TITLE
Custom tab images are invisible. Posible error at "get_Width()" function.

### ISSUE THREAD

**Issue by StickySli** [indiff/qttabbar#285]
**Describe the bug**
After updating to v.1.5.5-beta.8_en.2022, the "appearance" using a "custom tab image" no longer works.

**Reproduce the process**
After hovering, the tab image disappears.

- Disable the "use custom tab image" under "appearance" and apply.
- Delete the QTTabBarException.log to clear the log trace.
- Enable the "use custom tab image" under "appearance" and apply.
- Hover over the tabs makes them black (text and image disappears).

**Screenshot**
![explorer_1USEkZnmLf](https://user-images.githubusercontent.com/77287361/201527557-dd7b8290-ba65-41f3-8c3f-faac4addbd93.gif)

**System environment**
- .NET 版本: 2.0.50727.9164
- 操作系统版本: 10.0.22000.0 Major: 10 环境: 64
- QT 版本: DevBuild: 04/11/2022 16:59:00 (2.0.50727.9164)
- 错误信息: DrawTab

 
**Upload error log [QTTabBarException.log](https://github.com/indiff/qttabbar/files/9997357/QTTabBarException.log)**

Reading through the log files it looks like the same error is repeated around the function "get_Width()":
```
Message ---
Parameter is not valid.
HelpLink ---

Source ---
System.Drawing
StackTrace ---
   at System.Drawing.Image.get_Width()
   at QTTabBarLib.QTabControl.DrawBackground(Graphics g, Boolean bSelected, Boolean fHot, Rectangle rctItem, Edges edges, Boolean fVisualStyle, Int32 index)
   at QTTabBarLib.QTabControl.DrawTab(Graphics g, Rectangle itemRct, Int32 index, QTabItem tabHot, Boolean fVisualStyle)
TargetSite ---
Int32 get_Width()--------------
```

PD: I'm the author of [qttabbar-dark-mode-skin](https://github.com/StickySli/qttabbar-dark-mode-skin/).

**Comment by indiff** [comment]
thanks ! i will fix it in the next version
