### ISSUE TITLE
Text Misalignment for ambiguous tab text.

### ISSUE THREAD

**Issue by Stuwot** [indiff/qttabbar#289]
Hello,
I found your fork of QTTabBar the other day when I was installing Windows 11. Am giving it a try now. Seems to OK so far. I've had a few Explorer hangs but I'm not sure whether they'd be down to QT or something else.

Regardless, I'll keep on using and evaluating!

One bug I have found, when you have 2 tabs open with the same folder names and it gives additional information as to which parent folder that tab belongs to...the additional context text is not aligned correctly when you increase the tab bar height.

I have my tab bar height at around 40 and you basically cannot see the additional text. The problem gets worse the taller you make the tab bar.

Hope this helps!

![QTTabBar Text Misalign](https://user-images.githubusercontent.com/9908658/204113063-6737e156-87ec-47bf-b72b-5dc4204f2d4e.jpg)

**Comment by Starfallan** [comment]
相同的bug，same bug

.NET 版本: 2.0.50727.9164
操作系统版本: 10.0.19045.0 Major: 10 环境: 64
QT 版本: DevBuild: 2022/11/4 22:17:55 (2.0.50727.9164)

**Comment by indiff** [comment]
这个问题在下个版本已经修复了

**Comment by indiff** [comment]
这个问题在下个版本已经修复了
