### ISSUE TITLE
按钮自定义图片功能无效

### ISSUE THREAD

**Issue by lystormenvoy** [indiff/qttabbar#29]
![ButtonStrip24_gray](https://user-images.githubusercontent.com/6795312/83233066-bc1c8580-a1c0-11ea-99dc-ef84442a0317.png)
![ButtonStrip24_black](https://user-images.githubusercontent.com/6795312/83233071-be7edf80-a1c0-11ea-8da8-6ce1309f6f8b.png)
我编辑原版的图标图片文件，重新制作了一套图标。但是在【选项】——【按钮选项】——【自定义按钮图像】中选择这个图片，点击应用后图标没有变化。如果我随便选择一个别的图片文件（无论什么尺寸）反而可以生效（当然效果乱七八糟）

**Comment by indiff** [comment]
![微信图片_20200530141950](https://user-images.githubusercontent.com/501276/83321232-b4241a80-a280-11ea-8aba-a6451121c4a8.png)
![微信图片_20200530141943](https://user-images.githubusercontent.com/501276/83321235-b5edde00-a280-11ea-84a3-7aa20b445d43.png)
[QTTabBar Setup_zh-CN.zip](https://github.com/indiff/qttabbar/files/4705185/QTTabBar.Setup_zh-CN.zip)

**Comment by lystormenvoy** [comment]
感谢，我手动在设置里换这图就是不行，尴尬

**Comment by lystormenvoy** [comment]
另外还有个问题，似乎安装了你这里发布的版本后，我的Xshell经常崩溃，事件查看器是因为
错误应用程序名称: XshellCore.exe，版本: 6.0.0.13，时间戳: 0x5b51acf4
错误模块名称: appresolver.dll，版本: 0.0.0.0，时间戳: 0xf78f212c
appresolver.dll似乎是系统Windows Explorer的组件
