### ISSUE TITLE
能否增加根据选择的上一个标签，上上个标签依次类推自动变色标签的功能

### ISSUE THREAD

**Issue by demonjxc** [indiff/qttabbar#290]
每次开一堆标签都不知道上一次选的是哪个

**Comment by indiff** [comment]
可以通过这里进行手动配置你的颜色，自动变色可以在启用暗色或者浅色模式的时候开启
![image](https://user-images.githubusercontent.com/501276/205256925-44255806-bd49-411b-bd34-93bc14290b34.png)
