### ISSUE TITLE
win10中安装后，标签显示很小

### ISSUE THREAD

**Issue by h3soso** [indiff/qttabbar#292]
安装后，启用qttabbar后，标前显示很小。请问如何解决？谢谢！
![1669943066604](https://user-images.githubusercontent.com/37650377/205191615-ea9900d3-974c-43cb-8475-46c276ced29d.jpg)

**Comment by indiff** [comment]
新版是可以配置标签的大小
![image](https://user-images.githubusercontent.com/501276/205256566-df4a6083-7797-4456-98dd-a8e5e0af8864.png)

**Comment by h3soso** [comment]
感谢您的回复，已经解决问题。谢谢！
