### ISSUE TITLE
Tab label looks oddly positioned

### ISSUE THREAD

**Issue by siswonugroho** [indiff/qttabbar#296]
**Describe this bug**
When there's two or more tabs with the same name, the label to distinguish between them looks oddly positioned (see screenshot). In this case I changed the tab height to 35 (Options > Appearance > Tab size) and it looks cropped to the bottom, but even in default height it doesn't aligned properly.

**Steps to Reproduce**
1. Open file explorer
2. Go to "Downloads" folder
3. Open another "Downloads" folder from different disk in new tab

**Expected result**
The label should be positioned correctly

**Screenshot**
![image](https://user-images.githubusercontent.com/33504481/211201254-041a3fef-3710-4355-9347-625f4136f618.png)

**System environment:**
  - OS: Windows 11 version 21H2
  - .net framework: 3.5
  - Software version: 1.5.5.0 beta 8
  - Focus, focus, focus; if there is no error log that cannot be reproduced locally, then this problem will not be resolved
**Upload error log (C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
[QTTabBarException.log](https://github.com/indiff/qttabbar/files/10368627/QTTabBarException.log)

**Comment by indiff** [comment]
Next version fixed
1.5.5.beta9
