### ISSUE TITLE
win10深色模式下卸载后存有白条

### ISSUE THREAD

**Issue by icooc** [indiff/qttabbar#30]
![image](https://user-images.githubusercontent.com/32039433/83310056-6fc35b00-a23d-11ea-973c-8687b124278f.png)

**Comment by indiff** [comment]
1. 卸载后删掉 C:\Windows\assembly\temp， 如果删不了可以重启删掉
2. 卸载后可以通过任务管理器，重启资源管理器。再看下效果
3. 检查这些文件是否卸载干净 C:\Windows\assembly\NativeImages_v2.0.50727_64\QTTabBar\
![还不行的重装电脑了](https://user-images.githubusercontent.com/501276/83324873-a2e80780-a29a-11ea-9e78-d4505c564c24.png)

**Comment by icooc** [comment]
> 1. 卸载后删掉 C:\Windows\assembly\temp， 如果删不了可以重启删掉
> 2. 卸载后可以通过任务管理器，重启资源管理器。再看下效果
> 3. 检查这些文件是否卸载干净 C:\Windows\assembly\NativeImages_v2.0.50727_64\QTTabBar\
> ![还不行的重装电脑了](https://user-images.githubusercontent.com/501276/83324873-a2e80780-a29a-11ea-9e78-d4505c564c24.png)
> 

还是不行，不知道需不需要修改注册表？

**Comment by icooc** [comment]
> > 1. 卸载后删掉 C:\Windows\assembly\temp， 如果删不了可以重启删掉
> > 2. 卸载后可以通过任务管理器，重启资源管理器。再看下效果
> > 3. 检查这些文件是否卸载干净 C:\Windows\assembly\NativeImages_v2.0.50727_64\QTTabBar\
> > ![还不行的重装电脑了](https://user-images.githubusercontent.com/501276/83324873-a2e80780-a29a-11ea-9e78-d4505c564c24.png)
> > 
> 
> 还是不行，不知道需不需要修改注册表？

强迫症看得好难受。。。

**Comment by simple-kid1412** [comment]
关闭文件夹,先设置系统为白色主题. 然后在次设置黑色主题. 就ok

**Comment by death4444** [comment]
时至今日还是这样。坑啊
安装版本：QTTabBar.Setup_v1.5.5-beta.9_zh.2023
系统版本：Windows 11 家庭中文版 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
![image](https://github.com/indiff/qttabbar/assets/26320543/e8b17af9-e07a-42cd-abab-1aaf40d99091)
参考过的卸载方案：
[https://www.yuque.com/indiff/qttabbar/fgb0zd](url)
[https://www.zhihu.com/question/392904392](url)
