### ISSUE TITLE
希望能有一个已打开的重复目录合并功能

### ISSUE THREAD

**Issue by fjqisba** [indiff/qttabbar#303]
事实上我在浏览器资源管理器的时候，经常会打开重复的目录，我非常头疼这些重复的目录。

先打开目录C:\Windows，此时再打开一个目录C:\Windows的快捷方式，此时Windows会帮我进行跳转，防止打开重复的目录。
然而实际情况常常是，我打开目录C:\Windows后，再打开一个新目录C:\，然后在新目录中定位到了C:\Windows，此时Windows就不会帮我进行去重了。

我想到的解决方案有两种:
1、增加一个重复目录合并按钮，人工进行点击合并。
2、增加一个重复目录自动合并选项，每次打开一个新目录，都会判定是否此目录打开，如果已打开，则直接跳转到旧目录

**Comment by indiff** [comment]
有一个插件是关重复的功能 
![1676128950231](https://user-images.githubusercontent.com/501276/218266528-a0b55efb-656f-4594-a701-db52925ea1fb.png)
TurnOffRepeat.dll
