### ISSUE TITLE
多个标签显示问题

### ISSUE THREAD

**Issue by yaomin-yang** [indiff/qttabbar#306]
您好，我在安装qttabbar并使用后，出现一个小问题；当打开文件资源管理器时，在win10主题浅色模式下，同时新建两个以上标签，会出现非当前标签内文字颜色变成白色，影响阅读，请问如何解决这个问题

![image](https://user-images.githubusercontent.com/61115399/217799628-16d6984e-2b9e-4f74-806e-43a24c09a582.png)

![image](https://user-images.githubusercontent.com/61115399/217799772-5798f197-97f3-46b1-9d5b-ff45b8c2108d.png)
[QTTabBarException.log](https://github.com/indiff/qttabbar/files/10696562/QTTabBarException.log)

**Comment by czz404** [comment]
标签外观，Close Auto Color 选上试试

**Comment by indiff** [comment]
按楼上写的方法， 关闭自动变色，然后设置对应的颜色就可以了
