### ISSUE TITLE
安装教程无效

### ISSUE THREAD

**Issue by ncnnnnn** [indiff/qttabbar#310]
**描述这个Bug**
安装教程无效 
https://www.ixigua.com/7149475511784669711
404 非常抱歉！您查看的页面找不到了..

**重现过程**
重现过程的步骤:
1. 点击 '...' https://github.com/indiff/qttabbar/releases
2. 打开 '....'  [安装教程](https://www.ixigua.com/7149475511784669711)
3. 滚动 '....'
4. 报错信息  404 非常抱歉！您查看的页面找不到了..

**期望的结构**
视频正常

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.5]
 - 重点、重点、重点；没有报错日志本地复现不了的话，那这个问题不会处理
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

**Comment by indiff** [comment]
链接已修复 
https://www.ixigua.com/7154932467751879183
