### ISSUE TITLE
toolbar background colour

### ISSUE THREAD

**Issue by MadMaxFAF** [indiff/qttabbar#313]
**描述这个Bug**
清晰的Bug描述.

toolbar colour resetting when opening explorer

**重现过程**
重现过程的步骤:
set the toolbar background to solid colour,
change colour and apply
close and reopen file explorer
toolbar colour has been reset

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: windows 11 ver 22h2
 - .net framework: 4.8.09032
 - 软件版本: 1.5.5 - beta.9_en2023
 - 重点、重点、重点；没有报错日志本地复现不了的话，那这个问题不会处理
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**

[QTTabBarException.log](https://github.com/indiff/qttabbar/files/10777581/QTTabBarException.log)

**Comment by indiff** [comment]
![1676857229065](https://user-images.githubusercontent.com/501276/219990262-9a498897-ef56-40a1-9737-8f856f99b9bf.png)
you can use this to close reset color
