### ISSUE TITLE
标签文字有锯齿

### ISSUE THREAD

**Issue by humphreygao** [indiff/qttabbar#32]
看一下对比，左边是标签上的文字，右边是EditPlus上的文字。

![aliasing](https://user-images.githubusercontent.com/52394598/84028769-e5f55980-a9c3-11ea-80bb-7a9ebf6ca631.png)

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/84342650-b1a6b680-abd8-11ea-9e66-a29386d999db.png)
没有启用cleartype吧？
![image](https://user-images.githubusercontent.com/501276/84342752-ee72ad80-abd8-11ea-8ae6-8815d8779f46.png)

**Comment by humphreygao** [comment]
TrueType是启用了的。升级显卡驱动并重启发现好了。
还有安装软件后，TortoiseSVN/TortoiseGit的icon overlays丢失，需要重新在注册表中设置图标优先级，不知道是不是普遍现象，需要单独提issue吗？
