### ISSUE TITLE
[Question] Can it be installed by `winget` ?

### ISSUE THREAD

**Issue by Ethkuil** [indiff/qttabbar#340]
```
$ winget search QTTabBar
Name     Id                Version Source
------------------------------------------
QTTabBar QTTabBar.QTTabBar 1.5.260 winget

$ winget install -e --id QTTabBar.QTTabBar
Found QTTabBar [QTTabBar.QTTabBar] Version 1.5.260
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/qttabbar/files/1.5.0.0%20Beta%202/qttabbar-v1.5.0.0b2.msi/download
```

I wonder whether the above is the `QTTabBar` of this repository. If not, would you mind adding the version of yourself into `winget`? Many thanks.

**Comment by indiff** [comment]
之前好像提交过， 但是没有收录进去
It seems to have been submitted before, but it has not been included

**Comment by Ethkuil** [comment]
在 [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues/30713) 里搜索了下，只找到：

- https://github.com/microsoft/winget-pkgs/issues/30713#issue-1028784945
- https://github.com/microsoft/winget-pkgs/pull/56620#issue-1190555422
- https://github.com/microsoft/winget-pkgs/pull/76226

并且不知为何我用 winget 安装这个版本并重启后并没有生效。

如果能提交一个 `indiff.QTTabBar` 之类的就再好不过了。

---

I searched in [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues/30713) and found the following:

- https://github.com/microsoft/winget-pkgs/issues/30713#issue-1028784945
- https://github.com/microsoft/winget-pkgs/pull/56620#issue-1190555422
- https://github.com/microsoft/winget-pkgs/pull/76226

BTW, I installed this version using winget and restarted, but it didn't take effect.

It would be great if there is something like `indiff.QTTabBar` in `winget`.

**Comment by indiff** [comment]
https://github.com/microsoft/winget-pkgs/pull/141262
