### ISSUE TITLE
安装1.5.2版本重启打开选项后就报错

### ISSUE THREAD

**Issue by YesterdayNEO** [indiff/qttabbar#35]
![Snipaste_2020-06-11_13-10-59](https://user-images.githubusercontent.com/63648842/84348563-d6565a80-abe7-11ea-84d3-43f533ca721e.jpg)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 QTTabBarLib.QTabItem.GetTextSize(String str, Graphics g, Boolean fTitle)
   在 QTTabBarLib.QTabItem.RefreshRectangle()
   在 QTTabBarLib.QTTabBarClass.RefreshOptions()

************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9151 (WinRelRS6.050727-9100)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
QTTabBar
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9147 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.30729.9135 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BandObjectLib
    程序集版本: 1.0.0.0
    Win32 版本: 2.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/BandObjectLib/1.0.0.0__973461f1cd23d8eb/BandObjectLib.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
WindowsBase
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9143 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/WindowsBase/3.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.ServiceModel.Web
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.594.9135
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.ServiceModel.Web/3.5.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.ServiceModel/3.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9149 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/SMDiagnostics/3.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
system.runtime.serialization.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.4506.9135 (WinRelRS6.030729-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Serialization.resources/3.0.0.0_zh-CHS_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.XML.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
System.Transactions
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_64/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
QTPluginLib
    程序集版本: 1.0.0.0
    Win32 版本: 2.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTPluginLib/1.0.0.0__973461f1cd23d8eb/QTPluginLib.dll
----------------------------------------
QTQuick
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
TurnOffRepeat
    程序集版本: 1.0.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
Interop.SHDocVw
    程序集版本: 1.1.0.0
    Win32 版本: 1.1.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/Interop.SHDocVw/1.1.0.0__973461f1cd23d8eb/Interop.SHDocVw.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9151 (WinRelRS6.050727-9100)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
PresentationFramework
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9143 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/PresentationFramework/3.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9143 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_64/PresentationCore/3.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
PresentationFramework.Aero
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9135 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/PresentationFramework.Aero/3.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationFramework.resources
    程序集版本: 3.0.0.0
    Win32 版本: 3.0.6920.9135 built by: WinRelRS6
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/PresentationFramework.resources/3.0.0.0_zh-CHS_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
Ricciolo.Controls.TreeListView
    程序集版本: 1.1.0.0
    Win32 版本: 64.0.0.0
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/QTTabBar/1.0.0.0__973461f1cd23d8eb/QTTabBar.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.9136 (WinRelRS6.050727-9100)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

![Snipaste_2020-06-11_13-26-58](https://user-images.githubusercontent.com/63648842/84348740-4533b380-abe8-11ea-8740-483884455614.jpg)
net framework3.5已经开启

**Comment by sunny7bit** [comment]
相同问题，win10 2004版
