### ISSUE TITLE
打开一个应用程序的快捷方式属性，打开文件所在位置，程序所在文件夹被打开，但是再点击上一页就会闪退

### ISSUE THREAD

**Issue by jianguotao** [indiff/qttabbar#361]
**描述这个Bug**
打开一个应用程序的快捷方式属性，打开文件所在位置，程序所在文件夹被打开，但是再点击上一页就会闪退
发现用everything, Zotero，只要是打开搜索到的文件夹或打开文献所在位置，都会导致QTTabBar打开后闪退

**系统环境:**
 - 操作系统: [win10]
 - 软件版本: [1.5.5 beta 9]
 - 重点、重点、重点；没有报错日志本地复现不了的话，那这个问题不会处理
**上传报错日志([QTTabBarException.log](https://github.com/indiff/qttabbar/files/14548722/QTTabBarException.log)QTTabBarException.log):**

**Comment by Mingtu2019** [comment]
https://www.yuque.com/indiff/qttabbar/ardaxa
参考链接设置一下，似乎可以解决这个问题
