### ISSUE TITLE
Opening options on QTTabBar crashes the Explorer.

### ISSUE THREAD

**Issue by GTMoraes1** [indiff/qttabbar#38]
Using the en-US version, whenever I click to open the options menu, it crashes the Explorer.
I've tried with the 1.4 and the latest 1.5.2, at the time of this writting.

Steps to reproduce:
- Install en-US QTTabBar
- Right click QTTabBar
- Select Options

It'll crash.

I'm currently running on Windows 10 x64 2004

**Comment by aquqma** [comment]
Same problem, Windows version 2004, when open control panel Explorer crushes
Tried to find solution, the only one is http://qttabbar.wikidot.com/forum/t-1597399/control-panel-in-new-window
But using that way, all folders from desktop open in new windows, not nice. And if I use an execution list(put control panel there) Explorer aslo crushes :(
P. S. On my second computer too, Windows version there is 2004

**Comment by indiff** [comment]
Please install .net framework 3.5

**Comment by GTMoraes1** [comment]
Installed .net framework 3.5 from Microsoft webpage
https://dotnet.microsoft.com/download/dotnet-framework/net35-sp1

Issue persists.

**Comment by sobuj53** [comment]
this issue is not resolved even after following the instructions.
