### ISSUE TITLE
点击选项，就崩了

### ISSUE THREAD

**Issue by zj23564** [indiff/qttabbar#4]
随意进入一个路径，然后点击选项，资源管理器就卡死然后崩掉

**Comment by indiff** [comment]
删掉这两个文件，再试试，老版本编译进去的文件可能有问题
C:\ProgramData\QTTabBar\QTQuick.dll
C:\ProgramData\QTTabBar\TurnOffRepeat.dll

**Comment by RemRemRemRe** [comment]
删了也没用.（我把整个目录的dll都删了也还是崩溃

qttab 1.4（2020）

系统版本:
win10 1909 18363.720 专业版

还可以给您提供哪些debug信息?
