### ISSUE TITLE
Windows 10 "Cycle selection with F2 while renaming" not working

### ISSUE THREAD

**Issue by tea2code** [indiff/qttabbar#42]
Hi, as the title says it seems under Windows 10 the option "Cycle selection with F2 while renaming" in "Tweaks" doesn't work. Selecting a file and pressing F2 starts renaming but another press doesn't have any effect. Disabling and enabling the option doesn't make any difference.

I'm running QTTabBar 1.5.2.0 Beta 2 under Windows 10 (Build 1703 and 2004 on another computer).

**Comment by indiff** [comment]
![GIF 2020-6-22 13-04-20](https://user-images.githubusercontent.com/501276/85250392-01af3400-b489-11ea-854b-dd9402a55e84.gif)
