### ISSUE TITLE
Bottom tabs settings

### ISSUE THREAD

**Issue by bonobbo** [indiff/qttabbar#43]
Hi and thank you to all that created and contribute to this brilliant extension. I hope I'm in the right place to ask for Qtabbar support and it's okay if I speak english.

My issue is this: I often use the tabs in the bottom view, but every time Explorer is closed and reopened only the tabs at the top are reopened, while the ones at the bottom are lost. How can I set Qtabbar to remember the tabs open in the bottom view as well? And how can I change the default tab for the bottom view (which is Desktop, while I would set it to Downloads or a music folder)?

Many thanks for any tips and support given; if this is not the right place to ask for help please tell me what forum or website I could use!

**Comment by indiff** [comment]
please download the lastest version
