### ISSUE TITLE
【v1.5.2】资源管理器打开的情况下，再打开控制面板会关闭已打开窗口

### ISSUE THREAD

**Issue by wishayne** [indiff/qttabbar#44]
我在选项里打开**捕捉新explorer窗口为标签**，在已打开资源管理器的情况下再打开控制面板，原有资源管理器窗口会闪一下之后关闭窗口，同时控制面板窗口也没有打开，但直接打开控制面板则没有问题，看怎么修复一下？

**Comment by pencilheart** [comment]
我也有这个问题，控制面板内的所有子页打开时都会把原先的资源管理器关闭。现在问题解决了吗？

**Comment by pencilheart** [comment]
目前比较流畅的方式就是把捕捉关掉了。。
