### ISSUE TITLE
QTTab Standard Buttons 工具栏放在最前面，在重启资源管理器后异常

### ISSUE THREAD

**Issue by SuniRain** [indiff/qttabbar#45]
win10系统，经过尝试，QTTab Standard Buttons 工具栏放在最前面（现在就QTTabBar与QTTab Standard Buttons两个工具栏）的场景下：
1. 只开启QTTab Standard Buttons 工具栏。
2.第一行QTTab Standard Buttons，第二行QTTabBar。
3.一行左边QTTab Standard Buttons，右边QTTabBar。
异常：
在重启资源管理器后（包括重启电脑），再次打开资源管理器，QTTab Standard Buttons渲染异常或者不渲染，QTTabBar能继续使用，再次关闭打开资源管理器后，QTTab Standard Buttons 与 QTTabBar 都消失了。

**Comment by WeiChen1992** [comment]
win10 2004,重启电脑之后标准按钮（工具栏）或者 Qttabbra会失效，必须重新 在资源管理器 选项 下面 勾上 。而且位置得重新布局。我的软件版本是1.5.3

**Comment by SuniRain** [comment]
你好 我已收到 谢谢
