### ISSUE TITLE
重启重启会失效

### ISSUE THREAD

**Issue by yyx3658** [indiff/qttabbar#47]
win10 2004 在资源管理器 选项 下面 勾上 Qttabbra 设置好之后，重启电脑有很大概率失效，又要重新勾选。

**Comment by WeiChen1992** [comment]
win10 2004,重启电脑之后标准按钮（工具栏）或者 Qttabbra会失效，必须重新 在资源管理器 选项 下面 勾上 。而且位置得重新布局。我的软件版本是1.5.3
