### ISSUE TITLE
安装后没有效果,点击后未出现可以选择Qttabbar的下拉菜单

### ISSUE THREAD

**Issue by shi900384** [indiff/qttabbar#5]
RT,安装后没有效果,点击后未出现可以选择Qttabbar的下拉菜单

**Comment by indiff** [comment]
可以说一下你的系统版本么？

**Comment by shi900384** [comment]
感谢关心回复,现已查明原因:我只点击了图标然而点击图标下方文字才有效,并且internet选项设置中未开启"启用浏览器第三方扩展"选项






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "春风化雨细如丝"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 下午5:33
收件人: "indiff/qttabbar"<qttabbar@noreply.github.com&gt;; 
抄送: "街角、愛依舊"<1092900384@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [indiff/qttabbar] 安装后没有效果,点击后未出现可以选择Qttabbar的下拉菜单 (#5)




可以说一下你的系统版本么？
