### ISSUE TITLE
标签显示白条，看不到文件夹名称

### ISSUE THREAD

**Issue by cgkings** [indiff/qttabbar#50]
如题，win10 标签显示白条，看不到文件夹名称，请问该如何修复
![1](https://user-images.githubusercontent.com/58586625/87114829-2a666480-c2a4-11ea-9c50-85f44bed6694.jpg)
![2](https://user-images.githubusercontent.com/58586625/87114833-2e928200-c2a4-11ea-9a17-39bf7578b95b.jpg)
![3](https://user-images.githubusercontent.com/58586625/87114852-33573600-c2a4-11ea-9b5a-31cfab0f6e29.jpg)

**Comment by pcloves** [comment]
可能是字体太大了，可以尝试改小字体，或者增加标签高度
