### ISSUE TITLE
The text color is wrong in the dark mode of win10

### ISSUE THREAD

**Issue by oldmenplus** [indiff/qttabbar#52]
win10的深色模式下文字颜色还是浅色模式的颜色，看不清，无法调整，卸载QttabBar后恢复正常

The text color in the dark mode of win10 is still the color of the light mode. It is not clear and cannot be adjusted. After uninstalling QttabBar, it returns to normal

**Comment by jiabaoyu** [comment]
浅色下我正常，深色模式下当前的工具栏UI和文字不会自动反色，好丑。

**Comment by oldmenplus** [comment]
> 浅色下我正常，深色模式下当前的工具栏UI和文字不会自动反色，好丑。

(´･Д･)」 我自己调一下颜色就好了

**Comment by jiabaoyu** [comment]
而且高分屏上缩放有点难受，图标不够清晰

**Comment by oldmenplus** [comment]
> 而且高分屏上缩放有点难受，图标不够清晰

Σ(ﾟдﾟ;)  我只有2k，了解不了

**Comment by indiff** [comment]
#
