### ISSUE TITLE
win10不生效了

### ISSUE THREAD

**Issue by SiMaLaoShi** [indiff/qttabbar#53]
![image](https://user-images.githubusercontent.com/28924681/88150983-ae213900-cc34-11ea-92cc-a1390a6da434.png)

**Comment by yyx3658** [comment]
我也有这个问题，每次开机要手动才生效。win10 X64 V2004

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/89361795-c26a3900-d6fe-11ea-8f78-b34cdb4b7f97.png)
我这块版本还是正常的， 请提供一下有没有异常日志？ D:\Users\qwop\AppData\Roaming\QTTabBar\QTTabBarException.log

**Comment by SiMaLaoShi** [comment]
> ![image](https://user-images.githubusercontent.com/501276/89361795-c26a3900-d6fe-11ea-8f78-b34cdb4b7f97.png)
> 我这块版本还是正常的， 请提供一下有没有异常日志？ \AppData\Roaming\QTTabBar\QTTabBarException.log

重新安装重启一下就生效了，好像是360的问题，公司的电脑装了360，对了有没有交流群什么的，每次都要上git看有什么更新的

**Comment by indiff** [comment]
感谢您的建议， 我建个交流群。谢谢！
