### ISSUE TITLE
左侧快速访问栏的交互

### ISSUE THREAD

**Issue by terrytw** [indiff/qttabbar#56]
![捕获](https://user-images.githubusercontent.com/24227628/88473179-83452680-cf4d-11ea-9f8e-cb8eaeb7a8f8.PNG)

快速访问的几个文件夹(包括下面的图片、文档、下载等)目前似乎是没有中键或者ctrl+点击打开新标签的功能，不知道是不是可以加上，这几个真的是特别常用，谢谢！

**Comment by 954187350** [comment]
+1

**Comment by indiff** [comment]
可以下载最新版本
