### ISSUE TITLE
2K分辨率下200%缩放时，显示有问题

### ISSUE THREAD

**Issue by leeoo** [indiff/qttabbar#6]
如题

**Comment by gothame** [comment]
我也是，一点选项还提示错误

**Comment by indiff** [comment]
这个需要加强得功能， 可能需要后面处理

**Comment by zhanghming** [comment]
@indiff 我电脑是4k屏幕的，安装之后显示不全，基本上用不了，不知道会不会有针对高清屏优化的计划，感觉这个工具还是很有用的

**Comment by angle233** [comment]
我也是，字体高度重叠，图标都重在一起的。
![重叠](https://user-images.githubusercontent.com/22028862/86109444-fac29a00-baf6-11ea-9240-1416c3dee57d.png)

**Comment by indiff** [comment]
可以使用新版
