### ISSUE TITLE
1.4版本 安装后无法启用

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#60]
系统：window7 64bit
.net framework 4.6.2
如图所示，无法勾选上面两个
![image](https://user-images.githubusercontent.com/35558611/89880400-c7dfeb80-dbf6-11ea-9d9f-77c595bcd79d.png)

**Comment by indiff** [comment]
在 IE 管理加载器里面，启用qttabbar，试一试
![image](https://user-images.githubusercontent.com/501276/92705956-b3724880-f386-11ea-9a9b-d42c84307075.png)
