### ISSUE TITLE
在新标签中打开指定目录

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#63]
能否支持下ctrl+左双击，而不是非得中击？我鼠标中键坏了![image](https://user-images.githubusercontent.com/35558611/90117078-fb527f80-dd88-11ea-8fbe-07e7c87d8c53.png)，支持下更灵活，希望支持下，而不是限制！

**Comment by indiff** [comment]
这个可以通过配置，ctrl+左双击 是打开命令提示符的功能。 你可以通过配置里面更改快捷键 
![image](https://user-images.githubusercontent.com/501276/90868395-60c9f000-e3c9-11ea-8529-a3cbedb77517.png)

**Comment by git10135405** [comment]
我说的是这个
![image](https://user-images.githubusercontent.com/35558611/90869682-23fef880-e3cb-11ea-9cd3-55f91d08aca5.png)

**Comment by git10135405** [comment]
> 这个可以通过配置，ctrl+左双击 是打开命令提示符的功能。 你可以通过配置里面更改快捷键
> ![image](https://user-images.githubusercontent.com/501276/90868395-60c9f000-e3c9-11ea-8529-a3cbedb77517.png)

我说的是这个
![image](https://user-images.githubusercontent.com/35558611/90869747-3a0cb900-e3cb-11ea-96e2-43dcc868d2b1.png)
