### ISSUE TITLE
在新标签中打开指定目录

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#65]
https://github.com/indiff/qttabbar/issues/63#issue-678288237
能否支持下ctrl+左双击，而不是非得中击？我鼠标中键坏了image，支持下更灵活，希望支持下，而不是限制！
![image](https://user-images.githubusercontent.com/35558611/90869782-4abd2f00-e3cb-11ea-87d7-7e0a3fcf33ed.png)

**Comment by git10135405** [comment]
People？

**Comment by git10135405** [comment]
有人在吗？

**Comment by indiff** [comment]
ctrl+双击已经被一个功能占用了
