### ISSUE TITLE
这个版本的qttabbar和国外版本的有什么关系和区别啊？

### ISSUE THREAD

**Issue by mylovesaber** [indiff/qttabbar#67]
国外版本：http://qttabbar.wikidot.com/qttabbar
以前就听说过这个使用过一段时间，这两天重新下载发现github出现了一个看着也差不多的，这俩项目有什么关系啊？
这个是语言精简版？

**Comment by indiff** [comment]
是另外一个开源分支的版本 sf.net/p/qttabbar；作者已经2013年后没维护了
