### ISSUE TITLE
如果按钮选项全都不选能否让按钮选项那一行空白的自动隐藏？

### ISSUE THREAD

**Issue by hellokkk4789** [indiff/qttabbar#69]

**Comment by indiff** [comment]
可以，这个功能我找时间开发一下

**Comment by Landius** [comment]
不能自动隐藏，但是可以手动隐藏
![批注 2020-09-01 195926](https://user-images.githubusercontent.com/11910028/91849022-fa2cb800-ec8d-11ea-92b4-7d0f94dbf531.png)
