### ISSUE TITLE
新建文件夹快捷键失效(ctrl+shift+n)

### ISSUE THREAD

**Issue by shaporlu** [indiff/qttabbar#7]
Win10 1803 企业版x64，安装qttabbar1.3和1.2版本，新建文件夹快捷键(ctrl+shift+n)和新建文件(ctrl+n)均无效。

**Comment by shaporlu** [comment]
经过测试，更改软件默认快捷键或者不勾选软件自带的创建文件夹快捷键一项后，系统自带新建文件夹快捷键恢复正常。

**Comment by indiff** [comment]
谢谢， 我看下这个问题，应该是以前代码的bug

**Comment by indiff** [comment]
问题已经修复， 下载新版试用下，：）
