### ISSUE TITLE
1.5.3beta 报错 值不能为空

### ISSUE THREAD

**Issue by Kennnnnnji** [indiff/qttabbar#70]
![image](https://user-images.githubusercontent.com/34367558/92393035-cb14bb80-f151-11ea-8a7d-b648cd04d5ce.png)

**Comment by dupontjoy** [comment]
我点设置，以及更改设置选项时，也老是这个报错
win10 2004系统

**Comment by liwangdong** [comment]
我也是win10 2004系统，点击选项，直接闪退了

**Comment by indiff** [comment]
新版本已经修复bug
