### ISSUE TITLE
打开设置时资源管理器闪退

### ISSUE THREAD

**Issue by Dopamine2333** [indiff/qttabbar#73]
最新版本1.5.3，windows版本2004，打开qttabbar的设置界面时资源管理器会闪退

**Comment by indiff** [comment]
提供一下 异常日志文件看下 C:\Users\indiff\AppData\Roaming\QTTabBar\QTTabBarException.log

有可能跟历史的配置项冲突了， 试一试删掉注册表配置

HKEY_CURRENT_USER\Software\QTTabBar

**Comment by indiff** [comment]
下载一下最新安装包，试一下.

**Comment by indiff** [comment]
![)Z0FQZ~2D{W2_P}Y%7BVBF](https://user-images.githubusercontent.com/501276/102452287-130e7d00-4075-11eb-964e-b1179d397494.png)
![1608186819(1)](https://user-images.githubusercontent.com/501276/102452294-1570d700-4075-11eb-9944-62d6f9fb257d.jpg)

1. 卸载QtTabBar
2. 注册表删除 HKEY_CURRENT_USER\Software\QTTabBar
3. 重新安装 QtTabBar,打开选项
 ![29 6EZ6{XC`%GE@N8@(O9V4](https://user-images.githubusercontent.com/501276/102452458-57018200-4075-11eb-9872-0cbce91a38f9.png)
