### ISSUE TITLE
捕获窗口这个命令不生效

### ISSUE THREAD

**Issue by dalaovip** [indiff/qttabbar#75]
**描述这个Bug**
捕获窗口这个命令不生效
**重现过程**
重现过程的步骤:
1. 点击 'unity在资源管理器中显示'.
每次都新建一个窗口而不是合并

**期望的结构**
希望可以合并窗口

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3]

**Comment by indiff** [comment]
我这边 win+e ; vs2010 在资源管理器显示； 命令行方式都是可以进入单窗口的。 点击 'unity在资源管理器中显示'具体是用了什么软件？

**Comment by sage9731** [comment]
JetBrains的全家桶Show in Explorer也遇到了同样的问题，试过了IDEA、WebStorm和PyCharm，都打开了新窗口而不是在已有的窗口新增标签。

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/97532439-4deb2180-19f1-11eb-93de-04e9132d333b.png)
检查一下这个选项是不是被勾中?
