### ISSUE TITLE
高DPI显示有问题

### ISSUE THREAD

**Issue by liuchanghuaX1** [indiff/qttabbar#77]
![image](https://user-images.githubusercontent.com/40064819/98429858-4e1ba900-20e4-11eb-84e6-8fd8086401e9.png)
截图**
**系统环境:**
 - 操作系统: [e.g. win10 2009]
 - .net framework: [e.g. 3.5]
 - 软件版本: [e.g. 1.5.3beta]

**Comment by Miaite** [comment]
去下载这个 http://qttabbar.wikidot.com/
此项目好像是个同名山寨版……

**Comment by neighbads** [comment]
我也遇到了。手动点 调节标签高度暂时解决

**Comment by VShawn** [comment]
@Miaite 啊 这...

我检查了代码，注释里的原始作者确实是那个日本人 Quizo，这个项目不知道是干嘛的，推送日志大部分是在修改readme.

https://github.com/indiff/qttabbar/blob/5f4a025ec47b7b25806b249d574a39ea24ac25ad/QTPluginLib/MenuType.cs#L3
