### ISSUE TITLE
可以在地址栏按中键新建指定标签吗

### ISSUE THREAD

**Issue by xylcxyfc** [indiff/qttabbar#78]
现在可以在主视图的任意文件夹中键新建打开指定标签，我记得以前的qttabbar在地址栏按中键可以打开指定标签，比如在“D:\Software”中的“D:\”上面按中键可以打开一个D盘根目录的新标签，试了下好像没有这个功能，还是设置里面有这一项我没有发现呢？

**Comment by vmpsdkblog** [comment]
同样需要这个功能，在选项里面也没找到这个功能。

**Comment by TE-Radium** [comment]
同时希望在左侧栏也能使用中键
