### ISSUE TITLE
鼠标双击关闭最后一个标签时报.net错误

### ISSUE THREAD

**Issue by shaporlu** [indiff/qttabbar#8]
软件很好用，比原版的方便很多，感谢开发者的用心与付出。

本次发现一个bug，即：
软件设置中设置为鼠标双击左键关闭标签时，关闭最后一个标签的时候会报Microsoft .NET 

 Framework错误，详情为：无法访问已释放的对象，对象名：“QTabControl”。

测试环境：
1.Win10 1803 x64 实体机
2.Win7 sp1 x64 虚拟机

![image](https://user-images.githubusercontent.com/28617551/74625081-e56f5380-5185-11ea-8862-da869e444fef.png)

**Comment by indiff** [comment]
谢谢反馈， 这是一个bug， 我来看下这个问题。

**Comment by shaporlu** [comment]
您的邮件已收到，若有必要我会第一时间回复。    (Your email has been received, I will reply immediately if necessary.)
