### ISSUE TITLE
在已打开控制面板的情况下点击任务栏资源管理器无反应

### ISSUE THREAD

**Issue by Jacobax** [indiff/qttabbar#80]
也不算没反应，应该说是后台激活控制面板（闪红但不前台弹出）
win10 19042

**Comment by indiff** [comment]
1.5.5.5-beta支持不捕获控制面板

**Comment by 445081431** [comment]
> 1.5.5.5-beta支持不捕获控制面板

还是有问题，先打开资源管理器再打开控制面板没有问题。
如果先打开控制面板，这时候点击资源管理器没反应。
