### ISSUE TITLE
打开“程序和功能”会导致现有窗口标签全部关闭。

### ISSUE THREAD

**Issue by neighbads** [indiff/qttabbar#81]
标签组中，添加"程序和功能"，打开标签组，所有标签会全部关闭。只打开一个“程序和功能”。
在已经打开的“程序和功能”窗口。重复上面操作，不会再出现。
同样的问题也出现在“网络连接”

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/104155968-308bf800-5423-11eb-8317-a8bf5d4f490e.png)
![image](https://user-images.githubusercontent.com/501276/104156099-65984a80-5423-11eb-9757-a8d3b1a8d6ed.png)

**Comment by neighbads** [comment]
你是选择了 “窗口行为-会话保存-恢复上一个会话所有标签” 选项吧。

选择标签组的时候，所有窗口都会被关闭，如果上面选项选择的是 每次启动一个新会话，其他标签就会消失不复原。

重新卸载干净，手动删除 C 盘所有数据，使用最新版本安装 可以复现。

**Comment by neighbads** [comment]
感谢作者的维护。

麻烦问下这个问题修复了么
