### ISSUE TITLE
优化建议（新建标签页指定位置、系统深色模式下显示优化）

### ISSUE THREAD

**Issue by Amwsup** [indiff/qttabbar#82]
**描述你想要的解决方案**
1 目前点击 + 号创建新标签，每次都是打开C盘
> 是否可以在【选项-标签行为】增加设置：新建标签页：可选“我的电脑”或者“剪切板”或者“左侧标签页”或者“自定义目录”

2 Win10【设置-个性化-颜色-应用模式颜色】为深色时，显示优化（如图）
> 
![image](https://user-images.githubusercontent.com/74750630/103187277-b9247780-48fe-11eb-972e-14bb22f820df.png)

**Comment by StLeoX** [comment]
还有，为什么会有提示音呢？逻辑是什么？

**Comment by indiff** [comment]
关闭win7 的兼容样式， 下载最新版本
