### ISSUE TITLE
只要点击设置百分百把系统卡停，5秒内无法操作。

### ISSUE THREAD

**Issue by Rereyuop** [indiff/qttabbar#83]
**描述这个Bug**
只要点击设置百分百把系统卡停，5秒内无法操作。这应该和 net 3.5 无关吧，一般默认是打开的。

**重现过程**
重现过程的步骤:
1. 点击 工具栏上的'设置'大按钮
2. 界面假死，无报错信息

**期望的结构**
可以正常打开设置界面

**系统环境:**
 - 操作系统: [win10家庭中文版19041.208]
 - .net framework: [3.5]
 - 软件版本: [1.5.3]

**Comment by indiff** [comment]
可以加qq群，里面有word文档详细解决

**Comment by indiff** [comment]
打开选项闪退的解决方案修订版 https://gitee.com/qwop/qttabbar/attach_files/581136/download
