### ISSUE TITLE
期望实现原QTTabBar以下功能

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#84]
希望能实现原QTTabBar以下功能：
1、Ctrl+左键单击“导航窗格”如盘符等，可以在新标签打开
2、Ctrl+左键双击“文件夹”，可以在新标签打开

**Comment by terrytw** [comment]
这个建议我之前也提过
https://github.com/indiff/qttabbar/issues/56
这里也有人提过
https://github.com/indiff/qttabbar/issues/78

希望作者考虑一下:)

**Comment by indiff** [comment]
收到

**Comment by StLeoX** [comment]
在新标签页打开，这个是通过中键击中的，然后可以修改设置吗？
比如改为：Ctrl+左键双击，这样符合习惯。

**Comment by terrytw** [comment]
> 在新标签页打开，这个是通过中键击中的，然后可以修改设置吗？
> 比如改为：Ctrl+左键双击，这样符合习惯。

qttabar 本质上是在windows窗口里模仿浏览器行为
而在chromium系浏览器里，中键和ctrl+单击打开新窗口，才是符合习惯的传统行为，你试一下就知道了
当然我觉得加上ctrl+双击，应该不困难，毕竟原本部分鼠标操作就有这个选项
