### ISSUE TITLE
请求更新.NET framework到4+

### ISSUE THREAD

**Issue by VShawn** [indiff/qttabbar#85]
win10已成为主流的当下，系统自带版本已普遍在4.0+，最新版本系统应该已经自带4.8了，软件仍然使用3.5的库显然不方便使用。而且鉴于国内网络，用户从微软获取3.5的库时有可能会失败或耗时非常久，会带来不好的安装体验。

我认为与其让大部分用户去安装3.5，不如让少部分用户去安装4.8，同时放弃掉xp用户。

**Comment by akimusume** [comment]
确实，3.5太低了，至少4.0吧，xp也支持4.0的

**Comment by indiff** [comment]
尝试了很久， 目前的问题是选项的配置页面可能要重写

**Comment by indiff** [comment]
其他功能好像可以正常使用，只不过打开选项会崩溃。
