### ISSUE TITLE
[疑问]另一个QTTabBar？

### ISSUE THREAD

**Issue by littlegao233** [indiff/qttabbar#86]
（这个issue不重要，只是表达疑惑）
（同时希望作者坚持开发，超越这个版本）
不太清楚QTTabBar前世，不过在Google上搜到了**另一个QTTabBar**，并且更新活跃（目测是闭源的）
有一些特别的功能(比如脚本功能)，不过也有缺点（比如无法把所有捕获自动放在同一个窗口中）

自行测试可用
http://qttabbar.wikidot.com/
![image](https://user-images.githubusercontent.com/46601807/104797068-53892400-57f6-11eb-8f69-5c232e4fa1fe.png)

**Comment by dupontjoy** [comment]
好像都不是原版,原版早就停更了
quizo这个以前一直在用,有顽固bug,后来换了tc就很少用了

这个版本的qt感觉稳定的多

**Comment by indiff** [comment]
1. QTTabBar国内优化版是基于 sf.net/projects/qttabbar/ (2012-06-17) 提交的最新代码改版的。这个版本原作者没有发布过，具体不知道什么原因。增添一些汉化特性，主要是为了方便国内用户使用；另外日本作者维护的Quizo官网版本的捕获窗口一直用着不习惯，所以该版本保留了捕获窗口这个好用的功能。
2. QTTabBar是一款可以让你在Windows资源管理器中使用Tab多标签功能的小工具。从此以后工作时不再遍布文件夹窗口，还有给力的文件夹预览功能，大大提高了你工作的效率。就像IE 7和Firefox、Opera那样的。QTTabBar还提供了一些功能插件，如：文件操作工具、树型目录、显示状态栏等等。
