### ISSUE TITLE
标签最小宽度限制问题

### ISSUE THREAD

**Issue by git10135405** [indiff/qttabbar#87]
如下图所示，目前最小宽度只能到50，切换时容易误点，希望可以放宽点，其实只要不大于最大宽度即可
![image](https://user-images.githubusercontent.com/35558611/104975822-b406a400-5a36-11eb-8119-1cdd51b69662.png)

**Comment by StLeoX** [comment]
嗯，这个最好是可以设定吧

**Comment by StLeoX** [comment]
嗯，这个最好是可以设定吧
