### ISSUE TITLE
中文文本文件 预览乱码

### ISSUE THREAD

**Issue by StLeoX** [indiff/qttabbar#88]
**描述这个Bug**
清晰的Bug描述.

不同的txt或者md文件，都是采取 utf-8编码，但是有的文件预览乱码，有的则不会。

我默认的txt编码是utf-8_BOM，是都可以正常预览的。

**重现过程**
重现过程的步骤:

**期望的结构**
对你期望发生的事情的清晰而简洁的描述.

所有的中文文本文件都是可以预览的；
或者在某处能够设定预览的编码。

**截图**
如果可以的话，截图说明问题

**系统环境:**
 - 操作系统: [e.g. win10]
 - win10
 - .net framework: [e.g. 3.5]
 - 4.8
 - 软件版本: [e.g. 1.5.3]
 - latest 1.5.4

**Comment by indiff** [comment]
1.5.5.5-beta版本修复
