### ISSUE TITLE
安装 卡在编译本地图像

### ISSUE THREAD

**Issue by hsy-design** [indiff/qttabbar#9]
v1.4 v1.3都卡在
![2020-2-21 10-55-51](https://user-images.githubusercontent.com/52811347/75000566-ab5dc480-5499-11ea-93b2-842b174cdcc3.png)
![image](https://user-images.githubusercontent.com/52811347/75000622-d7794580-5499-11ea-81fc-3e05ae228df3.png)
但软件能使

**Comment by indiff** [comment]
会不会是多个软件安装冲突 ?

**Comment by hsy-design** [comment]
> 会不会是多个软件安装冲突 ?

这个应该不会，我只装了几个简单的软件，火绒 有道云笔记之类的常用软件，系统是win10 lstc

**Comment by shaporlu** [comment]
在我这里安装会在这个界面卡一小会儿，也是“编译本地图像这里”，需要等一会儿才安装完。

**Comment by luhua2018** [comment]
确实是，我在这最少得卡了10分钟，不过总算是装上了。

**Comment by gongway** [comment]
这一步是会卡住几分钟，最后都会安装成功

**Comment by indiff** [comment]
.net 3.5 安装编译需要时间
.net 4.0 编译时间很短，
但是很遗憾 .net 4.0 版本还有一个致命的bug未修复
