### ISSUE TITLE
missing windows dark theme detection and appearance settings

### ISSUE THREAD

**Issue by igpit** [indiff/qttabbar#90]
with dark theme selected in windows, qttabbar visual style in explorer (highlighted alternating rows) looks really bad

**Comment by LeSnake04** [comment]
agree

**Comment by Bobbsterman** [comment]
I also agree.
If it helps, the relevant registry keys are here:
**Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize**
Specifically: 
**AppsUseLightTheme**
