### ISSUE TITLE
4k分辨率下显示问题

### ISSUE THREAD

**Issue by BlankWhite** [indiff/qttabbar#91]
**搜索框和tab标签加号**
![Snipaste_2021-01-22_08-59-21](https://user-images.githubusercontent.com/11631255/105431613-e6134280-5c90-11eb-9f04-91613d3b9163.jpg)
![Snipaste_2021-01-22_09-04-15](https://user-images.githubusercontent.com/11631255/105431618-e7446f80-5c90-11eb-87b5-c6005169ed7a.jpg)
)

**Comment by indiff** [comment]
高DPI的问题希望有大神解决，我不是这个领域的目前还没找到解决方法
