### ISSUE TITLE
清空文件预览所有项目后无法打开设置

### ISSUE THREAD

**Issue by Fan-iX** [indiff/qttabbar#94]
**描述这个Bug**
清空文件预览的所有项目后无法打开设置

**重现过程**
重现过程的步骤:
1. 在设置中清空文件预览
2. 点击 应用
3. 试图再次打开设置面板，资源管理器崩溃。

**系统环境:**
 - 操作系统: win10
 - 软件版本: 1.5.4
 - 在windows sandbox中同样无法打开设置面板

**Bug原因**
 - 注册表HKEY_CURRENT_USER\SOFTWARE\QTTabBar\Config\Tips中 ImageExt 和 TextExt 两项为`[]`时，打开QTTabbar设置面板会导致资源管理器崩溃
 - 另外导出设置导出的.reg格式有错误（REG_SZ项内部的`"`应为`\"`）

**Comment by indiff** [comment]
把异常日志提供一下
