### ISSUE TITLE
点击“选项”，资源管理器卡死并重启。

### ISSUE THREAD

**Issue by bennieniu** [indiff/qttabbar#95]
点击“选项”，资源管理器卡死并重启。

**点击上方的“选项”按钮，资源管理器卡死并重启**
重现过程的步骤:
1. 点击 '选项'
2. 资源管理器卡死并重启

![image](https://user-images.githubusercontent.com/25980157/108792554-80321780-75bc-11eb-9c0e-348e2df220dd.png)

**系统环境:**
 - 操作系统: Win10
 - 软件版本: 当前日期最新版

**Comment by indiff** [comment]
https://gitee.com/qwop/qttabbar/attach_files
查看一下闪退解决方案

**Comment by bennieniu** [comment]
> https://gitee.com/qwop/qttabbar/attach_files
> 查看一下闪退解决方案

还需要重新安装qtabbar吗，

**Comment by bennieniu** [comment]
安装了.Net 3.5，重新安装qtabbar，点击选项，还是卡死
![image](https://user-images.githubusercontent.com/25980157/108798940-ee310b80-75c9-11eb-91b8-8307a1c7ed0f.png)

**Comment by bennieniu** [comment]
可以了，感谢
