### ISSUE TITLE
快捷键冲突bug

### ISSUE THREAD

**Issue by JeffCheung85** [indiff/qttabbar#96]
**描述这个Bug**
清晰的Bug描述.
使用快捷键操作跟win自己的冲突了

**重现过程**
重现过程的步骤:
快捷操作下，
选择上一个标签改成alt+left
选择下一个标签改成alt+right
保存后
按alt+left
会进入上一页，并不会跳到上一个标签

**期望的结构**
期望正常跳转到标签页

**系统环境:**
 - 操作系统: [win10]
 - .net framework: [e.g. 不清楚]
 - 软件版本: [ 1.5.4]

**Comment by indiff** [comment]
![image](https://user-images.githubusercontent.com/501276/117382610-7e1bfb80-af11-11eb-934d-67a93c5577c5.png)
默认的快捷键是可以使用的
