### ISSUE TITLE
系统声音

### ISSUE THREAD

**Issue by NationalConan** [indiff/qttabbar#98]
在打开文件管理器时，有系统声音发出。

**Comment by NationalConan** [comment]
> 在打开文件管理器时，有系统声音发出。

**Comment by NationalConan** [comment]
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎7/‎8
操作系统内部版本	19042.804

**Comment by indiff** [comment]
请检查一下声音方案是否修改过？
![image](https://user-images.githubusercontent.com/501276/116329733-8f248880-a7fe-11eb-9158-6b6b76165c6b.png)
